### ISSUE TITLE
Set up third-party risk assessment with Infosec

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#10]
We need to have a third-party risk assessment performed for Freshdesk, we need to fill in Infosec's Google Form.

**Comment by faucomte97** [comment]
Infosec's Google Form has been filled in, and Infosec got back to us asking us to send the 8-page form to Freshdesk.

**Comment by faucomte97** [comment]
Questionnaire sent to Freshdesk.

**Comment by mrniket** [comment]
Freshdesk have come back, @faucomte97 can you contact infosec please?

**Comment by faucomte97** [comment]
Sent questionnaire back to Infosec, waiting for result of risk assessment.

**Comment by faucomte97** [comment]
Emailed infosec asking for updates, waiting for reply.

**Comment by faucomte97** [comment]
Infosec replied, they're working through their back log. ETA is in 2 weeks.

**Comment by faucomte97** [comment]
First nudge sent last week, new nudge sent today. Waiting on reply.

**Comment by faucomte97** [comment]
Infosec mentioned they'd try to finish the assessment Friday last week. Will try and see this week if they've finished it.

**Comment by faucomte97** [comment]
Infosec have come back with approval and the report.
