### ISSUE TITLE
Promote Rapid Router Teaching Resources Demo

### ISSUE THREAD

**Issue by darcie-gomer** [ocadotechnology/codeforlife-admin#1006]
Demo creation task: [#262](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-design/262)
[Demo video](https://drive.google.com/file/d/1JvO_evB0OD9eTa92zEkXCIcy37jE8DtX/view?usp=sharing)

We have a new one minute demo video to show where to find the Rapid Router teaching resources and how to use them. We now need to share and promote this demo to our users.

**Comment by lauracumming** [comment]
Stale
