### ISSUE TITLE
Prep 'How to run a usability test' presentation

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1009]
- [ ] Create a 'How to run a usability test' presentation for the team and beyond
- [x] Add to calendar and send out invites

**Comment by darcie-gomer** [comment]
Resources:
https://www.nngroup.com/articles/usability-testing-101/
https://docs.google.com/presentation/d/1xUSxref5RoN1On3bxG0Bmk_5a3WvrRfoTTSrfbCzqXU/edit#slide=id.g7f3f6833d6_1_0
https://www.figma.com/file/ji3JYDRNjl7hnmSgPrliOz/Intro-to-UXR-(Grad-Training)?type=design&node-id=105-26&mode=design&t=kPqiIxub48thEzsA-0

**Comment by darcie-gomer** [comment]
https://docs.google.com/presentation/d/1UJ-EaYzzRm0nkGbWhXK3oZjtO8rrpQQsyQ7p0gy-xmA/edit?usp=sharing
