### ISSUE TITLE
Slides for introduction

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#103]

**Comment by mrniket** [comment]
https://docs.google.com/presentation/d/1Atqj7IB2XnFzKG-C8gAWTPGn241VoZuZ5tP9jmo0W1Y/edit?ts=5dce6bf9#slide=id.g6b03f5c83d_0_15

**Comment by mrniket** [comment]
Looks good! I think we should add a video of the bots in the Ocado/Code for Life introduction as well, it could be inspiring 😊

**Comment by lauracumming** [comment]
We only have a couple of minutes - remember - it’s about testing the game... let’s discuss later?
