### ISSUE TITLE
Knowledge share with team on having user centric mindset

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1033]
- [ ] Prep presentation
- [ ] Book in slot with the team to deliver

**Comment by darcie-gomer** [comment]
Merged with [#1009 ](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-admin/1009)
