### ISSUE TITLE
Flesh out student projects for Cranfield

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1057]
This is for a robotics/engineering student doing a masters. If successful and a student wants to work on a brief we will mentor them through the project. 

We need to add details to the briefs here: https://docs.google.com/document/d/1ZlklQNZdlMNCLdPSk5dk3f4ueGcIPDWr/edit?usp=sharing&ouid=108383205802561683495&rtpof=true&sd=true

and here:
https://docs.google.com/document/d/1ghEDMIPLaJElnVcTQZ-qzVF3VrieZEhD/edit?usp=sharing&ouid=108383205802561683495&rtpof=true&sd=true

Summary goes here: https://docs.google.com/spreadsheets/d/1cceWiKCB2jS4NcRbfgfM6K28d2fmDJOWDUT9HBfczps/edit?usp=sharing

**Comment by lauracumming** [comment]
Studentship Details:
Students: Postgrads - MSc (Robotics)
Duration: 4months (mid Apr-mid Aug)
Supervision needs: 0.5hr every two weeks
Futher time: High-level review - poster, thesis, publications (if any) for IP sensitivity

**Comment by lauracumming** [comment]
@SKairinos please check the first brief and add to where needed.

**Comment by faucomte97** [comment]
Added more details to mine. Still need to iron out a few details
