### ISSUE TITLE
Easter newsletter draft

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1060]
Create content for newsletter.

- [x] Theme
- [x] History 
- [x] Puzzle
- [x] Spotlight
- [x] Robotics workshop story with pics

**Comment by rdcruzCFL** [comment]
@lauracumming  What do you want from me?

**Comment by lauracumming** [comment]
Please could you find something historical and link a puzzle somehow - can be RR or Python.

**Comment by lauracumming** [comment]
@rdcruzCFL I've done this now.

**Comment by lauracumming** [comment]
With Duncan for review
