### ISSUE TITLE
Review and amend teacher guide sheets

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#107]
Check they make sense and are consistent.

**Comment by lauracumming** [comment]
All the new PDFs are in here ready for review:
https://drive.google.com/open?id=1qufI2lB2gUoPLE9UOrIFnRRbqfuQnyTo&authuser=l.cummingsare@ocado.com&usp=drive_fs

**Comment by mrniket** [comment]
@lauracumming  the PDFs are reviewed 😊
