### ISSUE TITLE
Update YouTube Cookie banner

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1076]

**Comment by lauracumming** [comment]
Version of this: Mouseflow. We also use Mouseflow on our portal; this provider offers a website analytics tool that helps us understand how our portal is used, and which areas are mostly used (e.g. by using heatmaps or by replaying your journey on our portal). Mouseflow uses cookies to record information such as when you click on or move your mouse, when you scroll, or press a key, what pages you visit on our website, how much time you spend on each page, and also information about the device you use (operating system, device type (desktop/tablet/phone), screen resolution, location (city/country), language, and similar metadata). Mouseflow does not collect any information on pages where it is not installed, nor does it track or collect information outside your web browser.

**Comment by faucomte97** [comment]
YouTube does not use a cookie.
Instead, used this task to remove the misleading text about the analytics 3rd parties in the banner where the text suggested there was further information below.
