### ISSUE TITLE
Break down task for automating volunteer support

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1078]
Translate whiteboard into tasks for this:
https://drive.google.com/drive/folders/1X4JqAQRmlU3C78IuSXX2O-Y_ZldP6y3C?usp=drive_link

**Comment by SKairinos** [comment]
I've had a rethink about how we can approach this. I propose we create a new contribute service that eve can work on. See the epic [here](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-workspace/81)
