### ISSUE TITLE
Document all datasets for other data objects

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1087]
https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/~/diff/~/changes/79/data/querying

**Comment by SKairinos** [comment]
why - 1 day? Also, blocked from doing what?

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3pVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07d56d125b105d5a9c7f7652d90b5ccef97db798/image_720.png" alt="image_720.png" />

**Comment by SKairinos** [comment]
won't be needed in the new system. data warehouse will store this info. database should not be used to store historical data. This should only be in the database if we have business logic that requires this data (which I don't believe we do - we only store it for analytical purposes)
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31f2c39cfa381c6b93812f909ac23ff95487fc11/image_720.png" alt="image_720.png" />

**Comment by SKairinos** [comment]
in every query where you say:
```teacher.school.id```
it should be:
```teacher.school_id```
This goes for all foreign keys

**Comment by SKairinos** [comment]
In the new system, the table name will be user_class
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--207b78db9d42318175b273502c5217cabee1e0cf/image_720.png" alt="image_720.png" />

**Comment by SKairinos** [comment]
"classes that have been deleted or are waiting to be deleted"
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9914a2b74d5bcd5b6cab6c33c76d0f7c409b7c65/image_720.png" alt="image_720.png" />

**Comment by SKairinos** [comment]
need to check accept_requests_until is not null first
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNERVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b4ca9458ca22c0a5f62485c4aa1eac195f9381c/image_720.png" alt="image_720.png" />

WHERE class.always_accept_requests = 1 OR (class.accept_requests_until IS NOT NULL AND class.accept_requests_until > NOW())

**Comment by SKairinos** [comment]
the field will be called "klass_id" in new system
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cace0f474bc196a10e417a62c601adf9ed00d2c6/image_720.png" alt="image_720.png" />

**Comment by SKairinos** [comment]
again, why -1 day?
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1faeb9fb40c2661eaec83bea68c3fc20ac831f6a/image_720.png" alt="image_720.png" />

**Comment by SKairinos** [comment]
blocked from doing what?<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5440873bc55c1daa83f416783e23c58a846fc68b/image.png" alt="image.png" />

**Comment by faucomte97** [comment]
Blocked from logging in.
Blocked_time is the date time at which user was locked out.
Lockout lasts 1 day or user can cancel it by resetting password.

Therefore a blocked user is a user where blocked_time is not null and the blocked_time is within the last 24 hours (if it is beyond 24 hours then the lockout has expired and the user can login).

**Comment by SKairinos** [comment]
I left comments
https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/data/querying

**Comment by faucomte97** [comment]
New change request https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/~/changes/84/data/querying
