### ISSUE TITLE
Investigate translating the labelling on the Blockly blocks

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1092]
**Summary**
We would like to be able to translate the language on the Blockly blocks in order to share our resources with schools in other countries, starting with Catalan. The blocks will still translate to English python at the later levels, it's just the UI.

**User story**
_As a Catalan speaking student
_I would like to be able to understand the labelling on the blocks 
_so that I can create algorithms for the van

**Outcome/deliverable**
- [ ] Investigate the task and if the update will allow this flexibility
- [ ] Create tasks on Zenhub in order to add to the next sprint

**Deadline**
This sprint

**Links**
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks

**Reviewer**
@faucomte97 or @SKairinos 

**People to contact**
@SKairinos  @lauracumming

**Comment by evemartin** [comment]
Notes on investigation:
- to change the default language of the blocks, change the script tag references to `'game/js/blockly/msg/js/en.js'` to refer to a different language. These are in `game.html`, `level_editor.html`, and `jasmine.yml`
- translated labels for custom blocks must be added to the corresponding js files, which can be found in `game/static/game/js/blockly/msg/js` - we then have to change the blocks to refer to these labels
- there are also json versions of the language files, but we need to add custom Blockly messages to the js files in order for them to appear - when the messages are only added to the json files, nothing shows up on the block

Notes on translation options:
- could use a dropdown on the level page - I found [this Github project](https://github.com/carloslfu/easy-i18n-blockly?tab=readme-ov-file) that adds a dropdown and hot-reloads the blocks when the user chooses a different language, so I think this option will be slightly lower effort as the way to do this in Blockly has been documented
- could have the user choose a language option on the settings page and use that by default everywhere on the site - I think this option would be slightly higher effort as it would involve work in both the portal and rapid-router repos
