### ISSUE TITLE
investigate and set up Google Analytics for tracking social media, and Gitbook

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1096]
**Summary**
We would like to track Social Media analytics in our Looker charts. We think the easiest way to do this will be using Google Analytics. We would also like to set up the Gitbook page views in Looker.

**User story**
_As a Code for Life Product Manager
_I would like to view the analytics in one place
_so that I can report back to stakeholders on which campaigns and content are successful

**Outcome/deliverable**
Tables in Looker of social media stats, and of Gitbook page views/downloads (if possible)

**Deadline**
This sprint

**Links**
https://www.linkedin.com/company/code-for-life-uk
https://www.instagram.com/codeforlife_uk/
https://www.facebook.com/codeforlifeuk
https://twitter.com/codeforlifeuk
https://www.youtube.com/@CodeForLife-uk

**Reviewer**
@lauracumming 

**People to contact**
@SKairinos @lauracumming

**Comment by evemartin** [comment]
Looker page and chart for data on how many visitors reach the site from social media/Gitbook: https://lookerstudio.google.com/reporting/dfa5a2b1-dc20-4718-9dfa-a38b5fa8568c/page/p_0frmm2yegd/edit
