### ISSUE TITLE
Rapid risk assessment and threat modelling templates

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1098]
**Summary**
We would like to create templates

**Outcome/deliverable**
tbc

**Deadline**
This sprint

**Links**
tbc

**Reviewer**
@SKairinos @lauracumming 

**People to contact**
@faucomte97

**Comment by faucomte97** [comment]
Migrated old RRA template to the new one
Migrated threat modelling info from old Miro board to new Miro board
Started migrating risk analysis info from old spreadsheet to new spreadsheet
Will need to ask for review from AppSec

**Comment by faucomte97** [comment]
Answered main comments from AppSec review. Closing this ticket as main work has been done, new tickets can be created as and when they are needed.
