### ISSUE TITLE
Text for portal - new Python module

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1099]
**Summary**
We would like to introduce the audience to the new Python based, Raspberry-Pi resources.
This will be what they are presented with on the website before logging in. Teacher, and student.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a teacher
_I would like to know what is available,  what it covers and what i will need to teach with the resources
_so that i can pick out what is relevant for my classes and what will help them to learn.

_As a student
_I would like to know what is available, what to expect, and what i need to learn with the course
_so that i can assess if i want to use it, or prepare myself for the lesson.

**Outcome/deliverable**
Document containing paragraph for teachers and for students.

**Deadline**
This sprint

**Links**
https://www.codeforlife.education/teach/
https://www.codeforlife.education/play/

**Reviewer**
@lauracumming @faucomte97 

**People to contact**
@lauracumming 

<img width="498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0plQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08fc99a2f73b8008361ec02adb0aa4624ea19a7d/Screenshot%202024-04-15%20at%2011.37.16.png" alt="Screenshot 2024-04-15 at 11.37.16.png" />
<img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05lQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afda408f9ed40816b9b7db4468a1a3eda8e9f385/Screenshot%202024-04-15%20at%2011.37.05.png" alt="Screenshot 2024-04-15 at 11.37.05.png" />

**Comment by lauracumming** [comment]
[Draft text here](https://docs.google.com/document/d/1eBrT0ezmDO2BNT9G0b6mTus-LJgZRod2-ENvFUl0gUk/edit?usp=sharing)

**Comment by rdcruzCFL** [comment]
@lauracumming 
My suggestions:
Teachers: Free lesson plans, videos and worksheets to support you in teaching Python programming to your students. We aim to provide a tried-and-tested, structured set of lessons that you can use in your classroom, no matter your own level of experience. 
Pupils: Use the slides or watch the videos to help you to learn to program with Python.

**Comment by lauracumming** [comment]
https://docs.google.com/document/d/1eBrT0ezmDO2BNT9G0b6mTus-LJgZRod2-ENvFUl0gUk/edit?usp=sharing
