### ISSUE TITLE
Create a feedback form for the CAS Conference workshop

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#11]
Please create a feedback form for use after the workshop session.

**Comment by mrniket** [comment]
@rdcruzCFL I have created a feedback form here: https://docs.google.com/forms/d/e/1FAIpQLSfdLZDRTNnCsdu4lS5mGzZwHsGNajxLcdpTzAqt7xeTL3cfAg/viewform

If it looks okay to you, I'll create a short URL for it that will be easier to share :)

**Comment by rdcruzCFL** [comment]
I'm afraid I cannot access that, Niket. I get this: 
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/9e3c0137-7c2b-4caa-b522-27edc01a94e7)

**Comment by mrniket** [comment]
Strange :/ I can give you the link to the editable form here: https://docs.google.com/forms/d/1vBnWsZ1uzx_KHWGXzO_uCACmqbEtOAYFllXmkn1sBtI/edit

and it's also in the team drive here: https://drive.google.com/drive/folders/1TQtos7s6JqPv8Tw7CG_b0kri1A3pXdRq

Do any of those links work?

**Comment by rdcruzCFL** [comment]
Yes, those worked, thanks. Sure, that's fine. Would you send me a shared short link please? I can't share it though, when I tried, I could see it any more. I wonder if you have created it to only work for Ocado employees and I am signed in with several users here? https://forms.gle/dNJiVUxNHKzFXUPi9

**Comment by mrniket** [comment]
Thanks for checking @rdcruzCFL! The settings were indeed wrong, I have adjusted them now so the link works for people outside of Ocado and I have also shortened it: https://forms.gle/wq2YhLc6wyevJAtn9

We will also not collect emails addresses in this form and no sign in should be required. I tested this in Chrome's incognito mode and it seems to be working
