### ISSUE TITLE
Update dev - contributor pages on Gitbook

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1114]
We need to update the pages on Gitbook once new dev container speed up is released.

**Comment by SKairinos** [comment]
[ready for review](https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/-M_6UDUiGoJDhr_OXetO/~/changes/262/become-a-contributor)

**Comment by SKairinos** [comment]
@lauracumming and @faucomte97 , can we have a quick call to discuss my changes today?

**Comment by faucomte97** [comment]
reviewed

**Comment by SKairinos** [comment]
@lauracumming, new docs are live. [here's the link to the new contributor setup docs](https://docs.codeforlife.education/software-developer-guide/dev-environment-setup).
