### ISSUE TITLE
Plan content structure on Gitbook

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1115]
for getting started/set up/external and internal contributors

**Comment by SKairinos** [comment]
Code for Life (https://code-for-life.gitbook.io/) (public) - this will sync to CFL’s workspace repo.

1. Intro
1. Services
    1. Link to service 1…
    1. Link to service 2…
1. Contributors
    1. Intro
    1. Prerequisites
    1. What you get
    1. Contribution process - zenhub, forking, pr reviews, definition of done
    1. Honourable mentions
1. Developer Guide
    1. Developing a Service
    1. Set up your dev environment.
    1. Frontend
        1. Tech stack
        1. Testing strategy
    1. Backend
        1. Tech stack
        1. Testing strategy
1. Link to student resources
1. Link to communications

Contributor Service (https://code-for-life.gitbook.io/services/contirbutor)
1. Intro
1. Change log
1. TBD

Rapid Router Service (https://code-for-life.gitbook.io/services/rapid-router)
1. Intro
1. Change log
1. Python commands
1. TBD

Portal Service (https://code-for-life.gitbook.io/services/portal) (public)
1. Intro
1. Change log
1. TBD

SSO Service (https://code-for-life.gitbook.io/services/sso) (public)
1. Intro
1. Change log
1. TBD

Python Package (https://code-for-life.gitbook.io/packages/python) (public)
1. Intro
1. Change log
1. TBD

Javascript Package (https://code-for-life.gitbook.io/packages/javascript) (public)
1. Intro
1. Change log
1. TBD

Communications (https://code-for-life.gitbook.io/communications) (public)
1. Newsletters (https://code-for-life.gitbook.io/communications/newsletters)
    1. Newsletter 1
    1. Newsletter 2
1. Quick Updates (https://code-for-life.gitbook.io/communications/quick-updates)
    1. Quick update 1
    1. Quick update 2
1. Blog posts (https://code-for-life.gitbook.io/communications/blog-posts)
    1. Blog post 1
    1. Blog post 2

Teacher Resources (https://code-for-life.gitbook.io/resources/teacher) (private)
1. Rapid Router (https://code-for-life.gitbook.io/teaching-resources/rapid-router) - TBD
1. Kurono (https://code-for-life.gitbook.io/teaching-resources/kurono) - TBD
1. Link to student resources

Student Resources (https://code-for-life.gitbook.io/resources/student) (public)
1. Glossary of computing terms
1. Intro to Python
1. Intro to Blockly

Full time - TBD
