### ISSUE TITLE
Work Experience preparation

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1122]
Prep tasks for work experience and send to people team

for:

- [x] Morning experience
- [ ] Week experience (UX)
- [x] Intern

**Comment by SKairinos** [comment]
@lauracumming, do you need anything from @faucomte97 or I on this?

**Comment by lauracumming** [comment]
No - this is going to be UX. I will need Dev to prep for the summer intern that we are welcoming in July though. Task to be created soon. :)

**Comment by lauracumming** [comment]
https://docs.google.com/document/d/1cVHNx1Qt_a5aMTbSZsaNp_O_oShH7FYmSLfI4Jtgkd4/edit?usp=sharing Please take a look @SKairinos @evemartin @faucomte97 

Add anything you feel is relevant - add details and help plan the time
