### ISSUE TITLE
Error copy for informing student when trying to join a class

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1125]
**Summary**
Students are left confused when presented with a generic error when trying to join a class with a class code.

**User story**
_As a student
_I would like to know why the request to join a class hasn't worked 
_so that i can inform the teacher

**Outcome/deliverable**
Create a doc with new error message copy

**Deadline**
This sprint

**Reviewer*
@faucomte97 

**People to contact**
@lauracumming

**Comment by SKairinos** [comment]
If a student enters a class code that either doesn't exist or is not currently accepting join requests, they'll be presented with this error message:

"The class code you entered either does not exist or is not currently accepting join requests. Please double check that you have entered the correct class code and contact the teacher of the class to ensure their class is currently accepting join requests."

Note that we cannot specify whether the class exists or not as this would be a security issue.

@lauracumming, do you approve of the above copy?

**Comment by SKairinos** [comment]
@faucomte97 , please also check the above

**Comment by faucomte97** [comment]
yes

**Comment by faucomte97** [comment]
approved
