### ISSUE TITLE
Investigate how we embed Raspberry Pi IDE onto our site for the new Python Hub

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1127]
**Summary**
We need to discover the tasks needed in order to embed the RaspBerry Pi IDE into a page on our site so that we can create an environment for the new Python Hub

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a student 
_I would like to access the IDE through the Code for Life site directly so that I don't have to click as many places.
_so that_ 

**Outcome/deliverable**
Task in backlog with estimates

**Deadline**
this sprint

**People to contact**
@SKairinos

**Comment by evemartin** [comment]
Results of discovery: by adding the Raspberry Pi [editor-ui repo](https://github.com/RaspberryPiFoundation/editor-ui) files and [bundle.js file](https://editor-images-staging.s3.eu-west-2.amazonaws.com/bundle.js) to our project, we can use their `<editor-wc>` custom HTML element to embed the editor IDE into our site. This element was made for a different specific project (Mission Zero) so we can't customize it, but we can look further into customization via using React components directly in [another ticket here](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-admin/1130). I have made a ticket to implement these findings and embed the IDE [here](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-portal/2312).
