### ISSUE TITLE
Order Kurono branded booth swag

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#113]

**Comment by lauracumming** [comment]
Can we align this with Kurono Common Room?
So that we can use for both 'events'?

The KCR doc is here: https://docs.google.com/spreadsheets/d/1lZBd5OAvWmXSmv2is7L82V3XYZFXlyuLVdQ4h9M4FUc/edit?usp=sharing

**Comment by faucomte97** [comment]
Swag (aka sticky walls, pull up banner, leaflets and posters) has been ordered. Invoice still needs to be received and paid off.
