### ISSUE TITLE
investigate how to customize Raspberry Pi embedded IDE

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/codeforlife-admin#1130]
In the other investigation ticket linked here, we found that it is possible to embed a Raspberry Pi IDE without customization, since the IDE was built for a specific other project (Mission Zero). This ticket is to investigate and see if there is any other way to embed the IDE so that it is customizable, i.e. through embedded specific React components rather than using the `<editor-wc>` tag that Raspberry Pi provides.

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/codeforlife-admin/1130?planning-poker) with Zenhub @evemartin @faucomte97 @SKairinos

**Comment by evemartin** [comment]
Previous raspberry pi ticket: https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-admin/1127

**Comment by evemartin** [comment]
Results of investigation:

There are two possible IDEs, the basic version which is just a code window and an output window and a fancier version with extra sidebar/top bar and whatnot - I think the basic version will be enough for us. The best way to add in the basic IDE is to download [this bundle](https://editor-static.raspberrypi.org/releases/v0.25.4/web-component.js) and add it to our repo's static js files, load it in a script tag on the appropriate page, and add this code snippet to the HTML:

```
<editor-wc
            class="c-editor__wc"
            data-editor-target="editor"
            output_split_view="false"
            code="print('Hello component')">
        </editor-wc>
```

From there, we can customize the "Run" button on the IDE and the div surrounding the IDE:
- to customize the run button, add `:root` (globally scoped) styling to either `--rpf-button-primary-background-color` or `--rpf-button-primary-text-color` to change the button background and button text color respectively. (The play arrow on the button is an SVG and cannot be changed)
- to customize the div surrounding, add `::part(editor-root)` styling. So far it looks like you can at least change margins, padding, and background color (and likely more), but attempting to modify shadow root-level variables doesn't work (the values you set here get overridden)

The basic IDE:
<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0R6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8011bd90004b85f2aeffe61793c4f4e643908578/image.png" alt="image.png" />

Note: generally, any variables defined in a `:root` global scope outside of the shadow dom can be overridden by adding styling to a`:root` global scope in a CSS file or style tag, it's just that not all of them are used by the IDE. 

Note 2: This is the code for the fancier version, I think it's a bit overkill for what we need
```
<editor-wc
        class="c-editor__wc"
        data-editor-target="editor"
        data-testid="editor-wc"
        load_remix_disabled="true"
        with_projectbar="true"
        project_name_editable="true"
        with_sidebar="true"
        use_editor_styles="false"
        sidebar_options="['projects','file','images','settings','info']"
        output_split_view="true"
        code="print('Hello component')">
</editor-wc>
```
