### ISSUE TITLE
Linkedin article - finish

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1134]
- [x] Finish LinkedIn article for refactoring part 1. 
- [x] Use James Donkin as inspiration.

**Comment by SKairinos** [comment]
@lauracumming, please [review](https://docs.google.com/document/d/18X1hyINpDFPFO1uKgWIA-M5ua6G2O9E0hgi1dBY3tbY/edit?usp=sharing)

**Comment by lauracumming** [comment]
Reviewed and suggested changes. Looking good!

**Comment by SKairinos** [comment]
[doc here](https://docs.google.com/document/d/1S2Mi2MDEAFd7HAQKHrKH_eDFU5G_Cpvegv_eip-GR3w/edit)
