### ISSUE TITLE
Inactive users email - check flow and label email accurately

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1162]
We would like to check the flow of the inactive users triggered email as we are emailing thousands of contacts a month and only a few hundred stay each time. We need to ensure this is definitely just users that have signed up for the newsletter and that they are not associated with anything else.

- [x] check flow for inactive users - ensure triggered emails are going to correct destinations
- [x] start naming convention for emails with this starting with 'newsletter'

**Comment by faucomte97** [comment]
## Subject matter 1 - the CfL newsletter

**Anyone** can subscribe to the CfL newsletter whether they have a CfL account or not. They can do so either during the registration process, or via the footer on the website.
The CfL newsletter mailing list is managed on Dotdigital. Like all instances where personal data is involved, a data retention period is required. In this case, we have set the retention period to 1 year (maximum allowed by Dotdigital automated programs).

The program works as follows:
- On the 1st Tuesday of every month, select all newsletter subscribers who haven't interacted with our emails in over a year or who have consented over a year ago.
- For each of those users, send the "[Newsletter - Inactive users](https://r1-app.dotdigital.com/Campaigns/Step/EasyEditor.aspx?id=960032)" campaign.
- Wait 7 days. This gives the subscribers a chance to resubmit their consent or the unsubscribe.
- After the wait is over, select the users that still haven't renewed consent and are still subscribed.
- For each of those users, send the "[Newsletter - Did you see our last email?](https://r1-app.dotdigital.com/Campaigns/Step/EasyEditor.aspx?id=960161)" campaign.
- Wait 7 days.
- After the wait is over, select the users that still haven't renewed consent and are still subscribed.
- For each of those users, remove them completely from the Dotdigital database.

The stats for these 2 campaigns have been checked and they add up to the expected amount of newsletter subscribers. These templates are not being triggered anywhere in the code and have not been mistakenly sent to users with actual Code for Life accounts.

Actions:
- [ ] There is a campaign that gets triggered when a user renews their consent, called "Yay! Thanks for staying!". The [report](https://r1-app.dotdigital.com/analytics/reports/emailcampaigns/959539#/summary) can be found in Dotdigital, however the actual campaign is nowhere to be found, so we need to find it and give it the "Newsletter" prefix, as well as update the social media icons.

## Subject matter 2 - the unverified users reminders

An investigation into the workflow for the unverified user reminders has unfortunately led to the discovery that the reminders were never active on the prod site and only on the dev and staging sites. [A PR](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-workspace/120) for this has just been made so we can remedy the situation ASAP.

No additional anomalies or actions have been identified in relation to these.

## Subject matter 3 - the CfL accounts data retention period

This relates to CfL user accounts, the data of which is stored on the CfL DB in GCP.
The data retention period here is 3 years.

The workflow is as follows:

- Every day at 2AM BST, [a job is run in GCP](https://console.cloud.google.com/cloudscheduler?project=decent-digit-629) which calls the [`users/inactive`](https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/api.py#L128) endpoint.
- The endpoint selects all inactive non-anonymised users (similar to [this query](https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/data/querying#delete-inactive-users)) and [anonymises](https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/api.py#L84) them.

Actions:
- [ ] There are no warnings / campaigns in Dotdigital to let users know that their account is about to be deleted. Implementing a warning could help retain users.

**Comment by faucomte97** [comment]
@lauracumming to review findings

**Comment by lauracumming** [comment]
Thanks @faucomte97 Yes - let's get the fix to production asap.
Ca we create tickets for:
A campaign for inactive registered users that we send out after two years, and one that is sent out at 2yrs 8 months. The final reminder at 2yr and 11 months we can also add in the information about data retention so that this covers both cases.

**Comment by faucomte97** [comment]
Tasks created.

https://github.com/ocadotechnology/codeforlife-portal/issues/2319
https://github.com/ocadotechnology/codeforlife-admin/issues/1164
