### ISSUE TITLE
Create suite of emails for inactive users on website

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1167]
We would like to create a suite of emails similar to those used in the verification process to help retain users.

- [x] Create suite of 3 emails

**Comment by lauracumming** [comment]
1st email draft
<img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a104f1fa14f6c44295e0f570f66e1f4b5434ba22/Screenshot%202024-07-15%20at%2014.42.30.png" alt="Screenshot 2024-07-15 at 14.42.30.png" />

**Comment by lauracumming** [comment]
Please review

**Comment by lauracumming** [comment]
Ready for review - email 1 (sent to @faucomte97 for links check)
<img width="1330" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFB1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a355c7a0622ddd84e9ec7bf8091c0b2a46bfbbc/Screenshot%202024-07-18%20at%2012.43.21.png" alt="Screenshot 2024-07-18 at 12.43.21.png" />

**Comment by lauracumming** [comment]
Ready for review - email 2 (sent to @faucomte97 for links check)
<img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFR1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d3f6c3c7f94003a04b051cce3794ea4c6798ef7/Screenshot%202024-07-18%20at%2012.43.34.png" alt="Screenshot 2024-07-18 at 12.43.34.png" />

**Comment by lauracumming** [comment]
Ready for review - email 3 (sent to @faucomte97 for links check)
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--699fc9eabdc2a1bed95012fbd49a40034690ce4c/Screenshot%202024-07-18%20at%2012.43.47.png" alt="Screenshot 2024-07-18 at 12.43.47.png" />

**Comment by faucomte97** [comment]
LGTM, however the buttons all link to the teacher login page, which assumes the user in question is a teacher and not an independent student. Is this OK?

**Comment by lauracumming** [comment]
I think that's okay.

**Comment by lauracumming** [comment]
Great, we can close and add time in to set these up in next sprint.
