### ISSUE TITLE
Investigate GA4 event data

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1168]
We have noticed that the events data being pulled in to Looker studio seems odd for the verification email campaigns.

- [ ] Check that the source and set up is correct for these events 

<img width="1785" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1128c3216b0dd4a84c9280523319f910b5b700c/Screenshot%202024-07-10%20at%2014.36.40.png" alt="Screenshot 2024-07-10 at 14.36.40.png" />

**Comment by evemartin** [comment]
<img width="1432" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGIvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--876689b6a273a5b8c7d2744d3ea6cb5d3cbd1b8f/image.png" alt="image.png" />
