### ISSUE TITLE
Add Python Den buttons to Tag manager

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1178]
**Summary**
Add Python Den buttons to Tag manager

**User story**
_As a product manager
_I would like to see how much traffic is interacting with the Python resources 
_so that I can ascertain how it is growing organically, and what happens when we market it on various platforms 

**Outcome/deliverable**
Tags and events to be added in order to track usage

**Deadline**
This sprint

**Links**
_Insert new Python Den levels page link here_

**Reviewer**
@faucomte97 @evemartin 

**People to contact**
@lauracumming

**Comment by EnoraHauduc** [comment]
I can start this task soon!

**Comment by evemartin** [comment]
@lauracumming we have added tracking for

- Python Den page views
- Python Den episode clicks (i.e. when people maximize/minimize episodes on the page)
- Python Den level clicks (i.e. when people click on a Python Den level)

Just wanted to check this with you before we closed the task!

**Comment by lauracumming** [comment]
Great. Thanks
