### ISSUE TITLE
Design questions and source case studies for report

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1180]
We would like to source some case studies from teachers, companies, contributors and students.

Design questions and send to relevant parties in order to start collecting examples.

- [x] Teachers
- [x] Students
- [x] Independent users
- [x] Student contributors
- [x] Businesses/Partners
- [x] Volunteers

**Comment by lauracumming** [comment]
Ready for review: https://docs.google.com/document/d/1KlEiKu_AQ6YsJxfvZSBezYVFI9HNGdLw8olR429IgbY/edit?usp=sharing

Please check for typos

**Comment by faucomte97** [comment]
Reviewed, added comments in doc

**Comment by faucomte97** [comment]
Reviewed, added comments in doc

**Comment by lauracumming** [comment]
Closing and sending out
