### ISSUE TITLE
Design brochure layout

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1182]

**Comment by lauracumming** [comment]
Please take a look and let me know your thoughts. I tried to give it more air than last year but i haven't added in navigation to the pages. Do you think you would use navigation if it were there or just go through page by page?

Note: I haven't added any links in yet so buttons don't work etc.

https://drive.google.com/file/d/1LpZNi_5Us6SGqEu_32CxOujVsCgiMC3m/view?usp=drive_link

**Comment by SKairinos** [comment]
![Image](https://github.com/user-attachments/assets/50b66fd9-9f33-4773-bcff-84bc4165b9d4)
subtext here seems to be wrong

**Comment by SKairinos** [comment]
and here
![Image](https://github.com/user-attachments/assets/fb788ea2-26db-451e-ad98-bc8000837458)

**Comment by SKairinos** [comment]
Read this and was impressed myself by how much we achieved this year!

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/7e111b34-53e9-4e01-87c2-e4463a1f4e12)
Incorrect caption here too

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/027f6aa6-2314-4ed0-9d5d-e7c7187f0aed)
this one too

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/bfc548eb-5911-40ce-ad6a-c6a143632d99)
again

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/e659ed32-1bea-470a-93ff-ca7a91779cc3)
I don't fully understand what the %ages relate to

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/591773dc-3da0-4092-8f25-07d072851ce1)
Replace with Barefoot video still

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/4a876f62-fcc4-4d13-b18d-2fc9a9b9d6bd)
Missing "said" page 20

![Image](https://github.com/user-attachments/assets/2ab25217-e11d-4942-8baa-644e99dd06f4)
And remove space

**Comment by faucomte97** [comment]
![Image](https://github.com/user-attachments/assets/02822f97-604b-43a0-9560-2f6086c4e293)
Wrong caption

**Comment by lauracumming** [comment]
Amends checked in
