### ISSUE TITLE
Newsletter for beginning of term

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1193]
Draft start of school newsletter - include CAS, Craig n Dave write up - back to school

**Comment by lauracumming** [comment]
Waiting for stories - to see which fits best with theme.

**Comment by lauracumming** [comment]
Can we have a better image for the CAS article?

**Comment by faucomte97** [comment]
There's the one of us looking extra tired

**Comment by lauracumming** [comment]
I found a different angle. Scheduled for Monday.
