### ISSUE TITLE
Prepare for soft release of Python Den

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1195]
**Summary**
We need to check all links and resources for the use of the new material

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a user
_I would like to find everything i need
_so that i can teach or learn from the Python Den

**Outcome/deliverable**

- [x] Check Portal
- [x] Check Gitbook
- [ ] Check Youtube

**Deadline**
This sprint

**Reviewer**
@evemartin 

**People to contact**
@lauracumming

**Comment by evemartin** [comment]
I have also made [this task](https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/rapid-router/1705) covering the technical aspects of preparing for the soft release, i.e. getting rid of old levels etc, which should be done at the same time as adding and checking links in this task

**Comment by lauracumming** [comment]
We did this
