### ISSUE TITLE
Create explainer video for set up process

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1202]
**Summary**
We would like to help explain what contributors need to do to get set up and would like to create a video for this.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a volunteer
_I would like to be able to set up my laptop
_so that i can contribute to the code for life project

**Outcome/deliverable**
Quick video walkthrough of set up process

**Deadline**
TBC

**Reviewer**
@faucomte97 

**People to contact**
@faucomte97 
@SKairinos

**Comment by SalmanAsh** [comment]
[Doc](https://docs.google.com/document/d/1TZ7rmLQGlrVnei5RT5KF6nF_OTXDLH9wGRukLBp5RXE/edit?usp=sharing)

**Comment by SalmanAsh** [comment]
@lauracumming @SKairinos @faucomte97 Ready for review.

**Comment by faucomte97** [comment]
LGTM, just need to make the voice track louder in the Docker installation video for Windows. Task created [here](https://github.com/orgs/ocadotechnology/projects/3/views/8?pane=issue&itemId=79297252)

**Comment by lauracumming** [comment]
I'll upload to youtube - Can you add the text to the set up docs so we can link the videos?

**Comment by faucomte97** [comment]
Superseded by new replacement of Docker Desktop with Moby / Docker CLI. Will need new videos.
New task here: https://github.com/ocadotechnology/codeforlife-workspace/issues/143
