### ISSUE TITLE
Scope project for CS in Schools

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1204]
**Summary**
We need to put together a proposal for CS in Schools for their cadet scheme.

**User story**
_As a Cadet
_I would like to gain industry experience in software
_so that I can learn and develop as a software engineer whist studying at university

**Outcome/deliverable**
Proposal and scope of project

**Deadline**
This sprint

**People to contact**
@lauracumming

**Comment by SalmanAsh** [comment]
We have two options:
[Leetcode](https://leetcode.com/) - Free but requires login.
[Neetcode](https://neetcode.io/practice) - Same as leetcode but does not require login (There are video solutions tho).

If we don't wanna give away the solution available on these websites,  we could get the questions from here and ask student to solve on their IDE. Then give test inputs on a white board to see if they correctly solved it.

**Comment by lauracumming** [comment]
Ready for review: [https://docs.google.com/document/d/1ma_wZzJ5R9j012NaiOTM1WYAMwNsED1PRPLX4BwBL_g/edit?usp=sharing](url)

**Comment by lauracumming** [comment]
@faucomte97 please can you take a look at this?

**Comment by faucomte97** [comment]
LGTM!
