### ISSUE TITLE
Create Wizard of Oz Donation button

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1205]
**Summary**
We would like to text how much traffic a donate button attracts, and then collect data to see how much people may be willing to donate of we changed to a charity. 

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a Product Manager
_I would like to understand the feasibility of charity status
_so that we can get support for our mission from external stakeholders

**Outcome/deliverable**
Design for button and feedback form

**Deadline**
This sprint

**Reviewer**
@faucomte97 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
![Image](https://github.com/user-attachments/assets/91295877-6c45-4cf3-b397-1a82dc67bfb8)

**Comment by lauracumming** [comment]
Ready for review

**Comment by andymales2** [comment]
Suggestions:

- Add a reminder that it's a non-profit organisation.
- Reinforce the message in a friendly way that we're not asking for money, just an _indication_ of a pledge if we were (just in case people were suspicious in entering an amount that would then take them to a payment page).
- Consider using radio buttons, like charities tend to for tips, e.g. £1, £2, £5, None, Other

**Comment by lauracumming** [comment]
Thanks @andymales2 The initial design used radio buttons with specified amounts, but when researching, I discovered this approach was better to discover insights alongside WTP. Users will likely add in their comments too. 

Thinking this may be helpful.

Will add those first two points in though. 🙏

**Comment by lauracumming** [comment]
![Image](https://github.com/user-attachments/assets/11c66111-ef29-4bbe-963a-a03e6347166f)

@andymales2

**Comment by andymales2** [comment]
That's much clearer, definitely feels more friendly and unambiguous that it's just a survey.
I'm not sure about the last sentence though - does donation have to provide a value? Are you asking the user to say how much they would donate, or just what they feel a fair donation might be?

**Comment by lauracumming** [comment]
Good point - I may have overly engineered the wording for it being just a survey.

**Comment by lauracumming** [comment]
![Image](https://github.com/user-attachments/assets/2a8726c6-af0d-4fa4-8ea3-06c472f0dc7d)
