### ISSUE TITLE
Handover to the team

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1207]
Sadly, we are also saying goodbye to the lovely Salman. 😔
This is a reminder to take some time to write up any notes and handover to the team.

**Comment by SalmanAsh** [comment]
TODO:

- [x] Tranfer ownership of contributor app to Stefan/Florian.
- [x] Tranfer ownership of dev setup document to Stefan/Florian.


Links:
[AWS](https://docs.google.com/document/d/1IcblOQIDHRP-z28LZGRtiKKawo_-Eyl7UEvvOu7ClZY/edit#heading=h.kc3cjguysqnh)
