### ISSUE TITLE
Prepare for adult Python lesson and volunteer training

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1208]
**Summary**
We are running an adult reskilling session in Luton through 'Careers you Love':

_Developwise CIC, Ocado’s Code For Life team and AUK Radio present Unlock the Power of Python: Introductory Session for Adults_

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As an instructor 
_I would like to have an agenda, slide deck and guidance for the session  
_so that i can run the class and enable volunteers to continue with the course.

**Outcome/deliverable**

- [x] agenda
- [x] presentation
- [x] handouts
- [x] logins and class set up in advance
- [x] guide for the volunteers
- [x] CFL Merch to give away
- [x] Consent forms for photos on the day

**Deadline**
Mid October

**Links**
Advert going out to attract attendees [https://docs.google.com/document/d/1c5DbPe7IZ4XFnRrI_rbS8C9BTQsd-gWD/edit?usp=sharing&ouid=108383205802561683495&rtpof=true&sd=true]

**Reviewer**
@faucomte97 @lauracumming 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
Started some [slides](https://docs.google.com/presentation/d/1fPet6N0LcxfdQ9sfRC7RHpwWm7P2yeS7if1pPpzXLDo/edit?usp=sharing)

**Comment by lauracumming** [comment]
@rdcruzCFL have a look when you get the chance

**Comment by rdcruzCFL** [comment]
@lauracumming  I have added some introductory slides

**Comment by lauracumming** [comment]
Looks good

**Comment by lauracumming** [comment]
Need to book in intro session and get volunteers set up with @faucomte97 and @SKairinos

**Comment by lauracumming** [comment]
Waiting on dates from Luton

**Comment by lauracumming** [comment]
All ready. @rdcruzCFL please confirm if you would like anything printed for the session.
I will bring some merch to give away.

Will we be asking them to sign up as Independents?

**Comment by lauracumming** [comment]
@faucomte97 please test this: https://app.lyssna.com/preview/c6791f9f8b45

**Comment by rdcruzCFL** [comment]
I assume that you are going to print the worksheets for 'pupils'? @lauracumming

**Comment by rdcruzCFL** [comment]
> Will we be asking them to sign up as Independents?
Unless you want to create a school account for them? I had not considered how they would sign up as they don't need RR or PD this week.

**Comment by lauracumming** [comment]
Ideally we will point them to sign up - so let's show them how to as an independent.

**Comment by lauracumming** [comment]
I can print the worksheets

**Comment by lauracumming** [comment]
Please also check this post session survey: https://app.lyssna.com/preview/9474f62c0938

**Comment by faucomte97** [comment]
@lauracumming Both surveys look good 😃
