### ISSUE TITLE
Scoping document for collaboration with Pinesphere

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1209]
**Summary**
We would like to propose a partnership with a company based in India. They have been using the products for 6 years and use it as part of their CSR model. They have software engineers that could help us build and can translate to Tamil for us.

**User story**
_As a stakeholder
_I would like to have a clear understanding of scope, expected timelines, roles and responsibilities in any collaboration.
_so that two companies can work together in harmony to produce new material and increase reach in India.

**Outcome/deliverable**
Scoping document and MoU

**Deadline**
This sprint

**Links**
To be added

**Reviewer**
@faucomte97 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
Ready for review: https://docs.google.com/document/d/1F5MwZG4vaFi8jZo6xNinOP_OA1F-McnCGgFSSUGpB8g/edit?usp=sharing

**Comment by faucomte97** [comment]
LGTM
