### ISSUE TITLE
Social media posts

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1211]
**Summary**
We need to post about the new features we have released recently.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a teacher,
_I would like to understand what is new at Code for Life
_so that I can check out the resources with my pupils.

**Outcome/deliverable**
Several posts about new features

- [ ] Facebook
- [x] Twitter
- [ ] LinkedIn
- [ ] Instagram

**Deadline**
This sprint

**Links**
No links

**Reviewer**
Ocado Group 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
🚀 National Coding Week is here! 🚀
At Code for Life, we're committed to empowering the next generation of problem solvers. Whether you're a teacher, parent, student, or independent learner, our FREE teaching resources are designed to make learning to code accessible and fun for everyone!
From our engaging games to editable slides and lesson plans, we offer everything you need to inspire and support critical thinking skills from an early age.
Ready to get started? Explore our resources today: [www.codeforlife.education](http://www.codeforlife.education/)
[Catch up on our latest news and events here](https://code-for-life.gitbook.io/newsletters/autumn-newsletter-2024)
#NationalCodingWeek #STEMEducation #CodeForLife #CodingForKids #EdTech #TechForGood #OcadoGroup

in review

**Comment by SKairinos** [comment]
LGTM

**Comment by lauracumming** [comment]
Scheduled
