### ISSUE TITLE
Remap Club packs to match new structure

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1216]
**Summary**
As we have updated Rapid Router and introduced Python Den, these packs will need updating.

**Outcome/deliverable**
Updated Slides and lesson plans saved to Gitbook.

**Deadline**
This sprint

**Links**
[https://code-for-life.gitbook.io/teaching-resources/v/rapid-introduction-to-python-code-club]

[https://code-for-life.gitbook.io/teaching-resources/v/code-club-resources-primary]

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming @rdcruzCFL

**Comment by rdcruzCFL** [comment]
@lauracumming 
https://docs.google.com/document/d/1o32Ocp5UvhiEXYCIWQgLd8O8r4R6pvDOqnCR_NbkYI4/edit

**Comment by lauracumming** [comment]
Looks good. Have added naming suggestions for the 3 clubs

**Comment by lauracumming** [comment]
Have hidden pages and merged. 
Please now add zipped folders for each 'club' so that there is a direct download @rdcruzCFL

**Comment by lauracumming** [comment]
@rdcruzCFL Has this been completed now?

**Comment by lauracumming** [comment]
Ive created a separate task for the zip folders
