### ISSUE TITLE
Add to Code for Life docs

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1219]
**Summary**
Continue to add to docs for contributors

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a contributor
_I would like to understand what I can help with 
_so that I can decide on an activity and get started

**Outcome/deliverable**
Add content to any pages that have 'coming soon'

**Deadline**
This is time-boxed

**Links**
[https://docs.codeforlife.education/](url)

**Reviewer**
@faucomte97 @SKairinos 

**People to contact**
@lauracumming

**Comment by faucomte97** [comment]
LGTM - merged
