### ISSUE TITLE
Python Den - changes to make to Beta

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#1223]
**Summary**
This is a list of Python Den changes to make. They will arise from our testing and user testing. 

**Outcome/deliverable**
Next release of Python Den

- [x] #1233
- [x] #1232

**Reviewer**
@lauracumming

**Comment by rdcruzCFL** [comment]
- [ ] Python 3 - Selection: Add slide 4 on relational operators in Python. 
- [ ] Python Den Level 16: is_animal_crossing() must be in an if-statement

**Comment by rdcruzCFL** [comment]
Please look at this document for ongoing issues.
https://docs.google.com/document/d/1-vaftmKNrOmOtUlupzGO4CPlKdDBloiGKY0FnCQSGf8/edit?usp=sharing

**Comment by lauracumming** [comment]
@rdcruzCFL is there a link to slide 4?

**Comment by rdcruzCFL** [comment]
@rdcruzCFL is there a link to slide 4?
>> No, it is just where it needs to go.
