### ISSUE TITLE
Digit<all> category and plan

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1224]
**Summary**
Digit<all> would like us to sponsor their awards

**User story**
_As a teacher
_I would like to understand what the category is and feel it is inspiring
_so that I can nominate my pupils for an amazing award

**Outcome/deliverable**
Doc containing category title and summary of category.

**Deadline**
This sprint

**Links**
tbc

**Reviewer**
@SKairinos 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
[CODE Award Supporters (1).pdf](https://github.com/user-attachments/files/17010965/CODE.Award.Supporters.1.pdf)

**Comment by SKairinos** [comment]
***Community Contributor***
At Code for Life we're growing and looking after a community of what will become the next generation of coders. We believe that everyone should have free access to the tools and support necessary to start learning how to code. However, now we'd like to challenge you to contribute something back to the community! What can you contribute that will inspire the next generation of coders to follow in your footsteps? We'd like to find out and see what you're capable off. Happy coding!

**Comment by lauracumming** [comment]
**_Community Catalyst_**
At Code for Life we're growing and building a community of problem solvers, some of whom will become the next generation of coders, game designers, or even club tutors! At Ocado, we believe that everyone should have free access to the tools and support necessary to start learning how to code which is why we created Code for Life. We challenge you to contribute something back to the community too! What can you contribute that will inspire the next generation of coders to follow in your footsteps? We'd like to find out and see what you're capable of. Good Luck!

**Comment by lauracumming** [comment]
I tweaked it a little.
