### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1231]
We would like to add and activate a donate button on our home page in order to collect contacts for possible support of our project.

- [ ] Add pop-up to button to collect email address and add to folder on Dotdigital
- [ ] Track clicks with Tag Manager

![Image](https://github.com/user-attachments/assets/cd36b585-1715-4e77-b002-7cb481d38b0f)

**Comment by faucomte97** [comment]
@lauracumming what does the button itself look like?

**Comment by lauracumming** [comment]
https://www.figma.com/design/9pMg7hFzK5YkjcnmwZsFl1/Portal-UI?node-id=319-11383&t=5GnZ53CWdxGUZxwF-1

**Comment by lauracumming** [comment]
LGTM
