### ISSUE TITLE
Python 3 - Selection: Add slide 4 on relational operators in Python.

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1233]

**Comment by SKairinos** [comment]
@lauracumming @faucomte97 , I don't understand this task. Where/what is slide 4?

**Comment by lauracumming** [comment]
I asked @rdcruzCFL the same question @SKairinos

**Comment by lauracumming** [comment]
This is an admin task

**Comment by lauracumming** [comment]
We still need clarification by the looks of it as I do not understand this either. Let's leave it for @rdcruzCFL to do

**Comment by rdcruzCFL** [comment]
It's fine. It is just an admin task for me!
