### ISSUE TITLE
Cadet scheme test

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1241]
**Summary**
We need to create a short test and application form for the Cadets scheme in order to select 3 students

**User story**
_As a Cadet
_I would like to answer some questions and test my knowledge
_so that I can demonstrate my skills to the Code for Life team

**Outcome/deliverable**
Short coding test and application form

**Deadline**
This sprint

**Links**
create doc

**Reviewer**
@lauracumming 

**People to contact**
@faucomte97 @SKairinos

**Comment by faucomte97** [comment]
https://docs.google.com/document/d/1-Uwe-gTxrUH63srz2iJ_JJHSYkbIJ7z2yJNz-_1QGf0/edit?tab=t.0

**Comment by faucomte97** [comment]
@lauracumming @SKairinos pls review

**Comment by lauracumming** [comment]
LGTM - Quite meaty for an application but let's run it by Megan if you are happy @SKairinos ?

**Comment by lauracumming** [comment]
Once this is reviewed by @SKairinos I will send to Megan with a date to kick it off.

**Comment by lauracumming** [comment]
Sending to Megan
