### ISSUE TITLE
Posters for printing - will tubes or stickers

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1252]

**Comment by lauracumming** [comment]
Please check draft for typos.
[Secondary_school_career_posters_2024.pdf](https://github.com/user-attachments/files/17291519/Secondary_school_career_posters_2024.pdf)

**Comment by lauracumming** [comment]
Waiting for sign off for print

**Comment by lauracumming** [comment]
Please check again before i send to print: https://drive.google.com/file/d/1hnIPeG7jLw3pF9BsHWFrTY3RGlqOl3X-/view?usp=drive_link

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
Sent to printer
