### ISSUE TITLE
Update videos for earlier sessions in Python Den

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1258]
**Summary**
We need to re-top and tail the newer versions for PD sessions 1-6

**Outcome/deliverable**
Updated videos uploaded to YouTube

**Deadline**
This sprint

**Links**
PD 

**Reviewer**
@rdcruzCFL 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
Ready for review. Please check links go to the new PD branded videos in YouTube

**Comment by faucomte97** [comment]
Sessions 1, 3 and 6 don't have the updated videos

**Comment by lauracumming** [comment]
Ready for review again - teachers and independents

**Comment by faucomte97** [comment]
LGTM
