### ISSUE TITLE
Complete Python Den course material

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1260]
**Summary**
We would like to now complete the course with 2D lists and modular programming so that they are ready for launch end of November.

**Outcome/deliverable**

- [ ] Lesson 12: 2D Lists
- [ ] Lesson 13 - Modular Programming
- [ ] String manipulation

**Deadline**
Mid-November

**Links**
Please add links to ticket once completed

**Reviewer**
@faucomte97 @lauracumming 

**People to contact**
@lauracumming

**Comment by rdcruzCFL** [comment]
@lauracumming  We also need string manipulation in here

**Comment by lauracumming** [comment]
LGTM, please go ahead with the video @rdcruzCFL 
I'm going to do this session myself to refresh my list knowledge, It's great!
