### ISSUE TITLE
Python Den launch marketing

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1271]
**Summary**
We are nearly ready to market Python Den and need to prep the posts in advance.

**Outcome/deliverable**
- [x] Social media posts x 2 (all four platforms)
- [x] Internal write up x 1
- [x] Newsletter story x 1
- [x] Add connection to Bett show (Stand) for a demo of the product

**Deadline**
This sprint

**Links**
Create launch doc

**Reviewer**
@faucomte97, Jelmer

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
Introducing Python Den, a brand new course from Code for Life! 

We're thrilled to share Python Den, our latest creation, developed to fill the gap left by Kurono and to support teens and adults in their Python journey through text-based programming. We’ve focussed our resources into upgrading our popular split-screen Python/Blockly levels, embedding an intuitive text-based experience, and integrating the open-source Raspberry Pi code editor. This unique blend of gamification and text-based coding is already making waves with over 15,000 views and 6,300 active users during our Beta release! 🎉

What is Python Den? Python Den is a fully-rounded Python programming course, packed with free lesson plans, videos, and worksheets. It’s designed to guide students, teachers, and independent learners from foundational syntax all the way to more advanced topics like loops and data manipulation. Each lesson is crafted to bring programming to life and make Python accessible and exciting for everyone.

Perfect for the classroom or at home, whether you're a seasoned computing teacher or a beginner, Python Den provides structured, easy-to-follow lessons that can be used alongside worksheets and videos. 

So, what are you waiting for? Get started with Python Den today and unlock a whole new world of programming! 

👉 [Link to Python Den]

**Comment by lauracumming** [comment]
![Image](https://github.com/user-attachments/assets/248cd8a3-deee-4345-a1d9-22fda893b9ab)
![Image](https://github.com/user-attachments/assets/e604cb71-0b69-4568-996c-15f8ed89e3e9)
![Image](https://github.com/user-attachments/assets/ca420fbf-b710-4b4c-9e85-6d5244d61869)
![Image](https://github.com/user-attachments/assets/3f594606-30ed-4157-9804-6a4f3f5eaf6e)

**Comment by faucomte97** [comment]
@lauracumming Text looks good but the stats are the "wrong" kind

**Comment by lauracumming** [comment]
Ready to roll
