### ISSUE TITLE
Python Den video extra

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#1275]
**Summary**
Additions to the Python Den marketing video

**Outcome/deliverable**
Add more to the Python Den video to include independent students too

**Deadline**
this sprint

**Reviewer**
@faucomte97 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
Ready for review: https://drive.google.com/file/d/1J4OA6qDJOk9jngiVjfg0lMbfYbjacxy1/view?usp=drive_link

**Comment by lauracumming** [comment]
@faucomte97 @SKairinos @duncanrussell-ocado 
We would like to get this out this week, so any amends please let me know asap.

**Comment by lauracumming** [comment]
Need to sort volume at the end!

**Comment by lauracumming** [comment]
- [x] add more slide video footage

- [x] Update wording

**Comment by lauracumming** [comment]
updated: https://drive.google.com/file/d/1JL7SonN1NimUDDUzldmahonJ0VnPHKc4/view?usp=drive_link

**Comment by SKairinos** [comment]
I have no change requests. This looks awesome; it's well paced, shows the keys points and, as Florian pointed out, the stranger things-ish music is fun. :)

**Comment by SKairinos** [comment]
@rdcruzCFL , your voice in the videos sounds eloquent!

**Comment by lauracumming** [comment]
Published on YouTube and ready to roll!
