### ISSUE TITLE
Prepare for CAS Workshop (materials)

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#13]
Can we have some of these:
- [x] LKS3–S3 and  LKS3–S6 stapled together* - faucomte97
- [ ] Pupil login card for each teacher (laminated) - rdcruz doing this
- [x] Extra class of pupil login cards in case of large session (*Workshop (extras) Pupil Login cards.pdf*) - printed - faucomte97
- [x] LR van [Teaching Resources/Teaching Packs/Assets/Page 6] - faucomte97
- [x] Ocado Tech bags - faucomte97
- [x] Check if we can get stickers in time - faucomte97

- [x] We have plenty of these but can you bring them please, @mrniket ?
- ks1_session_3
- ks2_session_2
- business cards

**Session attendee packs:** Pupil login card, teaching resource examples (1 of each) and business card
**For general handout:** teaching resource examples and business cards

- [x] Prepare packs - faucomte97
- [x] Put all digital resources on accessible drive for workshop (rdcruz)

**Comment by faucomte97** [comment]
I've printed the L/R vans page 10 times. Since each page has 3 vans, I assumed that is OK if we aim at having one van per person, for 30 people. Is this in fact correct, @rdcruzCFL?

**Comment by rdcruzCFL** [comment]
Yes, that's great, thanks @faucomte97
