### ISSUE TITLE
Prepare for CAS Workshop (script)

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#14]
Finish the script https://docs.google.com/document/d/1EJnlob3t3x8E6PJ-29hyXc5xq9y1e3ikqTxfoImt_1w/ for the day 
To do:
- [x] Create classroom 
- [x] Create pupil accounts 
- [x] Create teacher users for event
- [x] Print login cards
- [x] Check the narrative and timing

**Comment by mrniket** [comment]
Hi @rdcruzCFL, I've reviewed the script and it looks good, I just have a few questions about the feedback form I have put in the google doc :)

**Comment by rdcruzCFL** [comment]
Do you think those points are resolved now, @mrniket ?

**Comment by mrniket** [comment]
Sorry for the delay @rdcruzCFL, I have resolved the points and unblocked the feedback form issue. Is this issue okay to be closed?

**Comment by rdcruzCFL** [comment]
I'm happy with it, yes. Thanks.
