### ISSUE TITLE
Instagram research

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#151]
Is it possible to use Instagram to target students? Would it be worth the effort? Comparison research needed. Am thinking a diary approach - a post a day - quite a commitment though. Would we be able to maintain it? What would we talk about - would it also be targeting coders and volunteers?

**Comment by lauracumming** [comment]
Is there a doc somewhere for this please?

**Comment by mrniket** [comment]
@lauracumming  Judging from the issue's description, this is a discovery/research task that would produce the doc

**Comment by mariaFernando** [comment]
https://docs.google.com/document/d/1fsB6ZTscmai9-1Wm7xn-lJUqkijM1_f-nDGDTqceIJE/edit
The document WIP @lauracumming

**Comment by lauracumming** [comment]
We have an instagram account now
