### ISSUE TITLE
Questionnaire for Kurono Common Room at BETT show

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#162]
Adapt existing questionnaires for Common Room to suit audience and environment.

**Comment by lauracumming** [comment]
Please check and comment.

https://docs.google.com/forms/d/1zcSKIii-j0xs7U4y5xGRMcI90sdNKX1KTwxvjnQ2u58/edit

**Comment by faucomte97** [comment]
Looks good to me Laura :)
