### ISSUE TITLE
CFL Newsletter

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#169]
Contents:

**1. News update
2. Case study (Ocado people)
3. Historical case study
4. Related user challenge (younger students)**

- [x] copy approved

- [x] prep on Dotmailer

- [x] Approved by Comms
- [x] Approved by the employee

- [ ] Send out

**Comment by lauracumming** [comment]
Homework story - user quotes

**Comment by lauracumming** [comment]
Topics for consideration:

Common Room Lates
Kurono update
Parent Page /wfh

**Comment by lauracumming** [comment]
https://docs.google.com/document/d/1wP6ldE3kdVr7PDvEhaD4UWXn_CGKZ-8WjaM_I4ieQxM/edit#

**Comment by rdcruzCFL** [comment]
First draft is here, @lauracumming 
https://docs.google.com/document/d/1nD1s16K1kIcCqhdBp-nPqO3M5ec6Gwz0WvO3ZWi01MQ/edit

**Comment by lauracumming** [comment]
sent to Duncan

**Comment by lauracumming** [comment]
Still waiting on payment
