### ISSUE TITLE
Learning objectives on worksheets

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#176]
Add learning objectives to worksheets 1, 2 and 3

**Comment by rdcruzCFL** [comment]
These are in the teacher guidance documents.

**Comment by rdcruzCFL** [comment]
Laura
- please remove the last part about picking up ten artefacts (including notes and solutions) at the end of the worksheet 2 teacher guidance as per v2
- I have added teacher guidance for worksheet/challenge 3

**Comment by lauracumming** [comment]
@rdcruzCFL  Do we need this card anymore?

**Comment by rdcruzCFL** [comment]
@lauracumming No, I don't think so
