### ISSUE TITLE
Investigate and export user and newsletter registrations for Dotmailer

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#188]
- [ ] Investigate which users were added to newsletter list before we added the sign up feature and separate

- [ ] Export list of users that **did** sign up to newsletter for dotmailer

- [ ] Export list of registered users for dotmailer

**Comment by faucomte97** [comment]
@lauracumming Do we still need this?

**Comment by lauracumming** [comment]
no - we completed it
