### ISSUE TITLE
Tweak job spec for SE role

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#190]
I think we need to be flexible and tweak this for an experienced SE2 or an SE3. 
We need to have options, and we need to act quickly to get the ball rolling.

Laura and Niket to tweak.

**Comment by lauracumming** [comment]
Edited and ready for review. 

https://docs.google.com/document/d/1OXxKg3npvwjl9nFGnohgXlIAIzjTAuJ79sdZzJPJzwA/edit

**Comment by mrniket** [comment]
Reads so much better! 😊 I've added my comments

**Comment by lauracumming** [comment]
Thanks. :)
