### ISSUE TITLE
3 year retention period for users

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/codeforlife-admin#23]
To enable us to continue to be GDPR compliant

**Comment by lauracumming** [comment]
Do we have the spreadsheet of users for this yet?

**Comment by mrniket** [comment]
Instead of deleting inactive users, we could just edit their records and remove all the personal data from there, that way our analytics are accurate without having to rely on another place to store metrics.

**Comment by lauracumming** [comment]
I think this is a good idea. 👍
