### ISSUE TITLE
Get approval to use Google Optimize

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-admin#239]

**Comment by lauracumming** [comment]
Have chased but Gareth is on leave until 23rd

**Comment by lauracumming** [comment]
Gareth is setting up a new contact etc - hopes to be done this week

**Comment by lauracumming** [comment]
Chased again - 28/7

**Comment by lauracumming** [comment]
Chased again with Assia copied in on 2nd September

**Comment by lauracumming** [comment]
Update from Gareth - call arranged on Wednesday 14th with Google

**Comment by lauracumming** [comment]
Gareth setting up call with OR to discuss options for OT, as they have a few concerns.

**Comment by lauracumming** [comment]
emailed 21st Oct - Gareth is OOO.

**Comment by lauracumming** [comment]
Now attempting to get free license approval
