### ISSUE TITLE
Write up Common Room late #4

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#245]
- [x] Write up minutes - Rebecca
- [x] Write up minutes - Laura

**Comment by rdcruzCFL** [comment]
https://drive.google.com/drive/u/1/folders/1aAsnJYTkyIYYHniYJEdIteAAlEdntgt4

**Comment by rdcruzCFL** [comment]
I think we need to do an analysis of 
- http://the.computing.cafe/
- https://groklearning.com/
- https://theeverlearner.com/

Do you agree, @lauracumming ?

**Comment by rdcruzCFL** [comment]
# 2 (Mark Mills) done
# 3 (Pete Marshman) done
