### ISSUE TITLE
Discuss with team what next steps are for Rebecca's new assessment sheet proposal

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#26]
@rdcruzCFL has come up with a new self-assessment sheet for Year 5 students and thinks it is more efficient and useful than the one currently in the teaching materials.
We should discuss it and figure out what the next steps are in implementing this.

**Comment by mrniket** [comment]
@rdcruzCFL @faucomte97 I think we decided to try and use the teaching resources cms for this? (Once it is ready)

**Comment by lauracumming** [comment]
@rdcruzCFL to use Googledocs and we will format from those
