### ISSUE TITLE
Prep for second CAS demo 

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#270]
CAS wants another Rapid Router demo in September.
Same stuff. Laura to support if needed.

**Comment by rdcruzCFL** [comment]
@lauracumming I would much prefer August as I am limited in time from September and most schools finish before us. Is this possible?

**Comment by lauracumming** [comment]
@rdcruzCFL to contact CAS and arrange the best way to move forward

**Comment by rdcruzCFL** [comment]
@lauracumming I am waiting to hear back from CAS

**Comment by rdcruzCFL** [comment]
This was completed and I have handed over a summary sheet to Sarah.
