### ISSUE TITLE
Python real life examples

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#274]
We would like some RLEs of how Python is used in different jobs. Famous people too? 

The idea is we can then introduce these into the Kurono resources somehow to help students understand how useful learning Python could open up many doors to potential careers. 

"Did you know...?"
"Cool Fact.."
"How is this used?.."

etc

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/1qilTW-wY_5KW0updn15ACLWw3sk6e58b1WL8u56tMJ8/edit
