### ISSUE TITLE
Kurono and the UK Curriculum

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#275]
A high-level document (table) that explains how we are linking to the UK curriculum through Kurono each of the challenges.

**Comment by rdcruzCFL** [comment]
https://docs.google.com/spreadsheets/d/1pdkKDM0Rh8KU07JTiZRi7V0H2K3F7jZBJrnlayCBr3k/edit#gid=0

**Comment by lauracumming** [comment]
@rdcruzCFL  Can you take us through this in our next meeting, please? :)

**Comment by lauracumming** [comment]
Looks good - I guess we park this now until we have completed worksheets, and then we can format?

**Comment by lauracumming** [comment]
Closing this to create a new task for design
