### ISSUE TITLE
Worksheet 1 update

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#276]
1. Please remove references to "don't import random" and add import random to the top of the code. It seems that you need to import now.
Worksheet 1, Teachers notes worksheet 1
Worksheet 2

2. Please remove the line break after current_cell = . The whole line should read:
 current_cell = world_state.get_cell(avatar_state.location)

**Comment by lauracumming** [comment]
amend new starter code too if in images

**Comment by lauracumming** [comment]
changes made (I think) but needs @rdcruzCFL to check and publish if okay, please

**Comment by rdcruzCFL** [comment]
- The default code showing in Student Challenge 1 - Introduction is only one line long. I thought we were using this

```
def next_turn(world_state, avatar_state):
    new_dir = direction.NORTH
    # Your code goes here  
    action = MoveAction(new_dir)
    return action
```
- The default code was wrong on Student Challenge 1 - The present day. I think I have changed it. I didn't click publish so I don't know if you can see the changes I have made. 
- Move in all directions: changed sentence about import to *Don't forget to add `import random` at the top of your program as you would normally do.*
- Clarified the comments in Student Challenge 1 - Investigate Location to 
```
new_dir = direction.NORTH # Let’s assume you were going to move North
next_cell = avatar_state.location + new_dir # Get the cell you would move onto
print("The coordinates of the next cell are", next_cell))
# Ask Kurono if you can move to that cell
print("Can I move onto this cell?", world_state.can_move_to(next_cell))
```

**Comment by rdcruzCFL** [comment]
We need to change the teacher guide as well, @lauracumming, yes?

**Comment by lauracumming** [comment]
Thanks @rdcruzCFL
