### ISSUE TITLE
Induction process for new starter

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#278]
- [x] Order laptop
- [x] draft welcome email
- [x] order mobile when details come through
- [x] Set up and prep 121 slides
- [x] Send links for logins and accounts
- [x] Prepare 1st week reading list email (Ocado / Dev / Education)
- [x] Invite to all CFL Slack Channels
- [x] Set up picnic/social
- [x] Set up call with Rebecca
- [x] Setup tech chapter meetings again
- [x] Share Definition of Done doc - https://docs.google.com/document/d/18IO-YFs_wZYr1zpEQTxQbRjnAMfxYcLC6m8VZ6etmfI/edit

**Comment by mrniket** [comment]
Just putting this here as something that would be useful to read once it is updated as well: https://docs.google.com/document/d/1uzDrEzW_HZH7pYdVcTRbFaIjLydsS9GLwIx6xQztsmc/edit

**Comment by lauracumming** [comment]
Thanks Niket - yes, please add anything I may have forgotten about. :)
