### ISSUE TITLE
Worksheet 2 update

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#292]
1. Please change student worksheet 2:
- Make the challenge task into a main task so that all pupils do it. The solution and teacher notes are in the Kurono Worksheets - Challenge Solutions document
- Then remove the _Your Artefacts_ task at the end of this worksheet
- The teacher guide will need parallel adjustments
If you solved task one by choosing another random direction, you might have just copied the original code. It is best to avoid doing this as it makes your program much longer than necessary and makes it much harder to make changes and debug later. 

Create a subroutine called get_random_dir() and use it to return a random direction. Think about where this would be called from and what code it will replace.

**Comment by lauracumming** [comment]
@rdcruzCFL Are you able to do the amends on Contentful, please?

**Comment by lauracumming** [comment]
not sure where this goes - 
'If you solved task one by choosing another random direction, you might have just copied the original code. It is best to avoid doing this as it makes your program much longer than necessary and makes it much harder to make changes and debug later.'

@rdcruzCFL can you review other changes though, and if okay - publish, please. :)

**Comment by rdcruzCFL** [comment]
- I published Images of artefacts by mistake...  Not sure if it was finished. 
- The content all looks good there, I have published the page

**Comment by rdcruzCFL** [comment]
@lauracumming

**Comment by lauracumming** [comment]
@rdcruzCFL Do we have some additional exercises we can add to the worksheets, please? I think we still need to have these for pupils that finish first.
