### ISSUE TITLE
Update the Getting Started section of the user guide

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-admin#296]
The login flow and the dashboard have or in the process of changing, therefore the user guide needs to reflect this

![image.png](https://images.zenhubusercontent.com/57616341bf93871ccd9ca73c/d6e58520-c770-4bc5-8e7d-af701b1d2c0d)

We might want to also add here the concept of the worksheets/challenges/levels and games for each class for the teachers.

**Comment by lauracumming** [comment]
Do we need one for teacher and one for student then?

**Comment by rdcruzCFL** [comment]
This is near impossible to use without a live preview. I have set up my GitHub account as asked but still can't see previews

**Comment by lauracumming** [comment]
I will DM you
