### ISSUE TITLE
Additional challenges for worksheets

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#303]
Based on the student pain points, we would like to create additional activities that support the students with using Kurono and add to the worksheets for testing.

**Comment by rdcruzCFL** [comment]
The worksheets are designed to be for a single lesson so these would need to be an additional set of exercises that the teacher could use to support/extend @lauracumming

**Comment by rdcruzCFL** [comment]
How about using some of Paul Curzon's Computation Thinking puzzles, with his permission of course? He does some very interesting off-line things http://www.cs4fn.org/puzzles/
Also, these: https://csunplugged.org/en/ 
These are relevant for both primary and secondary.

**Comment by rdcruzCFL** [comment]
I have created a document of debugging exercises and code comprehension that might be useful as well.
I have included some on Rapid Router because I thought they might be useful in the newsletter
https://docs.google.com/document/d/1nODJ4XJ6J7Dzxjsp76--zQym2QB6nh7JSy_bpRDh9wk/edit#
