### ISSUE TITLE
Update teacher guides for worksheets 1 and 2

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#304]
Now we have updated the challenge sheets for 1 and 2 we need to reflect any changes in the guides for the teacher

**Comment by lauracumming** [comment]
@mrniket we will need PDF permissions working for this too in order to proceed

**Comment by lauracumming** [comment]
@rdcruzCFL Are you okay to do these updates now?

**Comment by rdcruzCFL** [comment]
I can't see the changes I made in the preview. Have I missed something? @lauracumming

**Comment by lauracumming** [comment]
@rdcruzCFL let me know if you can now.

**Comment by rdcruzCFL** [comment]
No, I can't @lauracumming
