### ISSUE TITLE
Research our student code inputs 

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#311]
- [ ] To examine whether there are any obvious user issues with the current set up that may need addressing (pain points)
- [ ] To create a record of the results (they are overwritten regularly) in dated tabs in the spreadsheet

If we look at the issues that are being revealed in the code that the students are trying in Kurono, we can see where they may be struggling. For instance, are they having problems with functions? In which case, can we add further to our worksheets or Kurono resources?

Would that be as a paragraph of text or could it be an additional offline activity?

**Comment by rdcruzCFL** [comment]
- Surely this isn't a manual task?!
 To create a record of the results (they are overwritten regularly) in dated tabs in the spreadsheet
- How can I tell which user entered which code? I thought it might be the number but that doesn't look right, most of them are 1. I am not sure how I can analyse the data unless I can track users in some way.

**Comment by lauracumming** [comment]
@rdcruzCFL I think it is fine for the code to be anonymous for now, as we are not measuring anything against this data, it is more as an insight into any misunderstandings.

**Comment by rdcruzCFL** [comment]
https://docs.google.com/spreadsheets/d/1pRDgfxisJwSCg0NYmSKQ3YJqKvaPZrjxbslsUs7M9-c/edit?ts=5f58b5e7#gid=51918813

**Comment by rdcruzCFL** [comment]
I have done this 
https://docs.google.com/document/d/1VvP4Onx9mFWz58wq2zf0hNR_RhQY7aCJP_s6_TMZBKE/edit

**Comment by lauracumming** [comment]
@mrniket We need to open up the permissions in the connected sheet so we can extract the data, please
