### ISSUE TITLE
Research Python teaching approaches

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#324]
Look at 
1. Sprint document  https://docs.google.com/document/d/14kjpymlvWRluNM5pMiphU9BMKzfDkKLUZ1c9fsoEyS8/edit
2. NCCE lessons https://teachcomputing.org/curriculum 
3. RDC's teaching approach
4. Google Code Labs https://codelabs.developers.google.com/

Come up with suggested approaches to teach (Python) programming for KS3/4

**Comment by rdcruzCFL** [comment]
I have finished the review and created a summary as well with a recommendation. It would be great if you could read both as the summary  draws heavily from the other document. 
Summary  https://docs.google.com/document/d/1tAPbj1dM805kIP5gOxfs2nUXXoTtAf9pxjudCTzPcfY/edit#
Detail https://docs.google.com/document/d/1ISDYWdVA9uPC8fmR20szztoethKs1Pzjy1oihG33aic/edit#

The (creative commons) GCSE NCCE materials are here: https://drive.google.com/drive/u/1/folders/1yjwxpAvcKjXDKHoxNrw4Gdu7cYg6HYNj

Let me know if you want to see any of the others - there are quite a lot of them!

**Comment by lauracumming** [comment]
Thank you @rdcruzCFL
