### ISSUE TITLE
Remove / Deal with user records on Dotmailer after 1 year of inactivity

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#331]
We need to figure out how to deal with the 3 year retention when it comes to records on Dotmailer.
Some users might just be registered to Dotmailer without having a CfL account.
What date do we go by? Last opened or last registered?

**Comment by lauracumming** [comment]
https://support.dotdigital.com/hc/en-gb/articles/360000151920-Using-programs-to-remove-contacts-from-address-books-and-to-delete-contacts-from-your-account

**Comment by lauracumming** [comment]
meeting in diary

**Comment by faucomte97** [comment]
Trying to sort this out as previous attempt didn't work - trying to test new flowchart on a test address book but it's difficult to put in data that covers all different cases.
