### ISSUE TITLE
Complete DPIA form

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#335]
- [x] Amends from Data protection team
- [x] Updates to data map

**Comment by faucomte97** [comment]
Waiting on Freshdesk assessment renewal from Infosec

**Comment by faucomte97** [comment]
Chased Infosec

**Comment by faucomte97** [comment]
Ticket #8126306

**Comment by faucomte97** [comment]
Messaged Freshdesk today

**Comment by lauracumming** [comment]
Freshdesk has completed the form. Now back with Legal team.

**Comment by faucomte97** [comment]
(with InfoSec team)*

**Comment by lauracumming** [comment]
Sent request to Infosec for Usability Hub use report

**Comment by lauracumming** [comment]
Freshdesk assessment complete! Next due March 2023

**Comment by lauracumming** [comment]
Infosec chased

**Comment by lauracumming** [comment]
Report received from infosec

**Comment by lauracumming** [comment]
Report sent to legal team
