### ISSUE TITLE
Incorrect answer in teaching resources

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#346]
"The answer in the teacher resources for level 75 doesn't give a full score. I had to google the answer on found it on github. 
I'm uploading the answer they have which actually gives full points. Please fix this on teacher resources please."

to do:

- [x] Update PDF with new image
- [x] handover to dev

https://drive.google.com/file/d/1Sa-7uIp7ew95ACtVmPIeMNUir-jWES67/view?usp=sharing

**Comment by lauracumming** [comment]
@faucomte97 Did we do this already?

**Comment by faucomte97** [comment]
Yes, closing now
