### ISSUE TITLE
OneTrust Cookie management

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#348]
Legal has stated that cookie banners need to be in place across our websites asap. 
OR and OT are using OneTrust as a tool to implement this consistently and we are finding out whether we need a new license or whether we can piggyback on the existing agreement.

We need to:

- [x] Contact Infosec
- [x] Contact Ocado team
- [x] Contact OneTrust
- [x] Create a cookie audit with name / functionality / purpose etc
- [x] Work with OneTrust to implement
- [x] ICO compliance

**Comment by lauracumming** [comment]
requested meeting with ocado contact

**Comment by lauracumming** [comment]
Permissions provided - we need to take a look

**Comment by lauracumming** [comment]
Need to categorise the cookies and send through to Legal

**Comment by lauracumming** [comment]
Design started - CSS to be added

**Comment by lauracumming** [comment]
Laura to update doc: https://docs.google.com/document/d/15xXWw7kA5pL-p7z-4DixeuMNELeUigBXDwpzhqNou5A/edit?usp=sharing

**Comment by lauracumming** [comment]
Ready for review; https://docs.google.com/document/d/15xXWw7kA5pL-p7z-4DixeuMNELeUigBXDwpzhqNou5A/edit?usp=sharing

**Comment by faucomte97** [comment]
Reviewed, added comments
