### ISSUE TITLE
In-house check of flow for teacher and students

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#354]

**Comment by rdcruzCFL** [comment]
**Used Test Class LX596**
Used **User Guide**: https://www.codeforlife.education/materials/Kurono_teacher_user_guide
- This doesn't mention how to set up a class. Is this deliberate?
- What is the purpose of assigning a worksheet to a class? I have gone on to worksheet 2. 
- When I tried loading Present Day II, it took a while but then looked the same. Can we just hide those for now?
- The pupil can't see Present Day II but the teacher can create them. 
- Is worksheet 1 supposed to be Present Day I: The Museum and worksheet 2 Present Day II?

**Setting up a game for a class**
- Can the guides etc. open in a new tab instead?
- What is the name supposed to be when you set up a game? 
- Maybe mention something about the worksheet being assigned and what that means?
- There is no mention in the user guide or challenge how to give pupils access to the game
- Add something about giving pupils a link or printed copy of challenge sheet?
- Recommend suggesting that the teacher demos and explains (Introduction) and allows pupils to read the introduction part of the challenge sheet before handing out login cards

 **Logging in as a student from that class** 
Pupil 1/RW1cj3HL
- Doesn't load in incognito mode (Chrome). I just get a "Building game world" message
- It does sometimes take quite some time (1 min+) to load the game. Can we do some load testing before asking a teacher to try it with a class?

**Doing the exercises**
- If the code crashes (e.g. forgot to import random), would it be possible to pause the player so they don't get the same error message spamming their console log?
- Is it possible to show line numbers for errors? I had a syntax error but it does not tell me which line of code is causing it. 

**Also, make sure the teacher would have what they need.**
- Yes, other than the above comments. 
- The only useful thing could be .py file of solutions so they can demo easily
