### ISSUE TITLE
Create a bank of questions for user research

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#368]
- The idea is to send out two questions a month for user research.
- Could be to do with anything text-based programming related for now.
- We want to avoid asking what features they would like -  but we can ask what they currently use etc.

**Comment by rdcruzCFL** [comment]
I have made a start on this in draft form. Perhaps you can discuss with the team?
https://docs.google.com/spreadsheets/d/14ORXRvzZqZ0J0mjiBOo-i9OQON1dwDzrNxTiwM2R8FE/edit#gid=0

**Comment by lauracumming** [comment]
thanks, @rdcruzCFL I will merge existing spreadsheet with this so they are just in once place. 👍

**Comment by lauracumming** [comment]
Linked to 'break time quiz' card on the design board

**Comment by lauracumming** [comment]
@faucomte97 take a look when you can and let us know your thoughts. :)
