### ISSUE TITLE
Update teaching pack - level 43

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#377]
Add alternative solution

**Comment by rdcruzCFL** [comment]
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/8e1cb489-c3ef-4c3a-be7b-251285356196)

**Comment by rdcruzCFL** [comment]
This currently only scored 6/10 but I think it should be 10!

**Comment by lauracumming** [comment]
Have we completed this as a dev task @KamilPawel

**Comment by lauracumming** [comment]
@rdcruzCFL Doesn't look like this exists yet. @faucomte97 is this possible without changing the entire scoring for RR?

**Comment by lauracumming** [comment]
@rdcruzCFL what do we want to do for this, have two answers or make this the higher score?

**Comment by rdcruzCFL** [comment]
If we can have two answers, great. Otherwise, I prefer the one I offered.
