### ISSUE TITLE
Teleporting snippet for cheat sheet

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#380]
We would like to introduce a snippet of code that allows students to teleport out of being trapped on the board. It will need to be to a random location to avoid them using it to gain faster results with the challenges.

To pinpoint the situation, we are thinking that they would need to use and **if statement**. 
If avatar to (the direction) teleport to safety etc

**Comment by rdcruzCFL** [comment]
I assume it will be something like:
action = TeleportAction()

The if is more complex. You don't want them teleporting as soon as they can't move in a given direction. Seeing as the locals lose their values each move, we can't easily count how many times they have been unable to move.

This would either rely on globals or have them write fairly complex code that loops trying alternate directions. I am not sure that either of these are ideal. 

Do you think the engine should do this? How difficult would it be to notice that a single avatar has tried to move unsuccessfully four times and then just teleport them?

**Comment by rdcruzCFL** [comment]
Given a get_random_dir() subroutine as in the worksheet solutions:
```
# Option 1
import random
def next_turn(world_state, avatar_state):
    new_dir = get_random_dir()
    
    # If the avatar cannot move, allow four attempts
    attempts = 0
    cannot_move = True
    while attempts < 4 and cannot_move: 
        next_cell = avatar_state.location + new_dir
        attempts = attempts + 1
        if world_state.can_move_to(next_cell):
            cannot_move = False
        else:
            print("I can't move that way! Choosing another direction...")
            new_dir = get_random_dir()
            
    if cannot_move:
        action = TeleportAction()
    else:
        action = MoveAction(new_dir)
    return action

# OR

# Option 2: Use a global
import random
failed_moves = 0

def next_turn(world_state, avatar_state):
    global failed_moves
    
    new_dir = get_random_dir()
   
    # Count every failed move and teleport if it reaches 4
    next_cell = avatar_state.location + new_dir 
    if world_state.can_move_to(next_cell):
        failed_moves = 0
    else:
        print("I can't move that way! Choosing another direction...")
        action = next_dir + get_random_dir()
        failed_moves = failed_moves + 1
        action = MoveAction(new_dir)

    if failed_moves == 4:
        action = TeleportAction()
    else:
        action = MoveAction(new_dir)
```

**Comment by lauracumming** [comment]
@rdcruzCFL  would this mean that the student would have to try all directions though before it is teleported?
We noticed in the classroom that they would try once and then give up as they could see they were surrounded.

**Comment by rdcruzCFL** [comment]
@lauracumming  Maybe so but they are writing code so move them around... They would need to disable their code and put in a teleport command in the scenario you describe. Would it be better to have a teleport button so they could just click it or would that just cause mayhem?!

**Comment by faucomte97** [comment]
Hi @rdcruzCFL, I had a look at this too and I was thinking we could save the students and teachers some hassle by simply implementing a method that would automatically check if the avatar can move in any direction. Something like this:

`import random

def next_turn(world_state, avatar_state):
    new_dir = get_random_dir()

    # If the avatar can move, move
    if world_state.can_move():
        action = MoveAction(new_dir)
    # If the avatar cannot move, teleport
    else:
        action = TeleportAction()
    return action`

I think this could be a good way of solving the avatar being stuck problem without increasing the complexity of the worksheets or lessons too much.

**Comment by faucomte97** [comment]
Need to:

- [ ] Create dev task for it
- [ ] Groom & prioritise it
- [ ] Let Rebecca know once we've implemented it

**Comment by faucomte97** [comment]
We've agreed to have `avatar_state.is_stuck()` instead of `world_state.can_move()`

**Comment by faucomte97** [comment]
The `TeleportAction()` will also have an in-built check of whether the avatar is stuck and only allow teleportation if the avatar is stuck.
We also might want to add a popup message to let students know that they can only teleport if they are stuck.
