### ISSUE TITLE
Error in worksheet 2 teacher solution code

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#381]
In Task 1 - with subroutines. The error and correction are below.
``` 
# With subroutines
# Task 1 - Choose another random direction (with additional subroutine)
import random
def next_turn(world_state, avatar_state):
    new_dir = get_random_dir()
    
    # Get details about the cell you would move into
    next_cell = avatar_state.location + new_dir 
    if world_state.can_move_to(next_cell):
        action = MoveAction(new_dir)
    else:
        print("I can't move that way! Choosing another direction...")
        action = MoveAction(get_random_dir())
```

**Comment by lauracumming** [comment]
Updated. New PDF to create and upload.

**Comment by faucomte97** [comment]
@lauracumming @rdcruzCFL I think the code should be `action = next_dir + get_random_dir()` instead

**Comment by dionizh** [comment]
Wasn't sure to bring this up in the meeting, as I wasn't familiar with the context and scope of this piece, but what if you still can't move to the second random direction? Is this probably called in another subroutine repeatedly until the character is able to find a valid direction?

**Comment by lauracumming** [comment]
@dionizh yes, it repeats until it moves.

**Comment by faucomte97** [comment]
Need to generate and upload
