### ISSUE TITLE
Review Rapid Router teaching resources

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#382]

**Comment by lauracumming** [comment]
@rdcruzCFL can you post the link to the location on here, please?

**Comment by rdcruzCFL** [comment]
Sorry, I thought I had! It must have been in a chat
https://docs.google.com/document/d/1wVtCZ38pWyccTPKOMoxz_ymV25OT2ijm4Xwuoz3Vg6w/edit#heading=h.mpt3ykuvrdb0

**Comment by lauracumming** [comment]
Need to create tasks for volunteers
