### ISSUE TITLE
DPA template

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#395]
Create a template with the legal team for schools to use with us.

Contact legal through Plexus.

**Comment by lauracumming** [comment]
Seek an example template from school

**Comment by lauracumming** [comment]
with legal

**Comment by lauracumming** [comment]
Agreed to not do individual contracts with schools. Legal to update Privacy page to cover us.

**Comment by faucomte97** [comment]
@lauracumming Should we close this now as I've created a new issue to do specifically with creating a doc as a DPA substitute? #406
