### ISSUE TITLE
Naming of the worksheets/challenges

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#397]
This task is to agree on the below.
The proposal is to call the challenges as follows:

**Present Day - The Kurono Time machine
Present Day - Lost in the museum
Ancient - Collecting the artefacts
21st Century - Sorting the good from the bad
Prehistoric - The Portal
Back to the Future - Resetting time**

They should correspond with the actual student tasks.

We will then need to create a Dev task and update in Wagtail and on the student and teacher Kurono dashboards.
When used in the smaller cards, the naming can shorten to the first part. 
On Hero cards and in the games table for teachers, they should be used in full.

**Comment by rdcruzCFL** [comment]
So worksheet 1 would be Present Day - The Kurono Time machine?
They sound good!
