### ISSUE TITLE
Investigate kurono game no.1

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#401]
We have a game that doesn't exist appearing in analytics.
Kurono/play/1 

It says the traffic comes directly or from the home page. But this doesn't make sense.
![Screenshot 2021-02-04 at 14.01.37.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/6cd9f475-9eef-4017-936d-3648431daadb)

**Comment by lauracumming** [comment]
![Screenshot 2021-02-10 at 16.48.45.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/a5f959ee-a6fe-4eb2-94f9-f19f4d722fd4)

**Comment by lauracumming** [comment]
I have found a helper for this and have a meeting set up next week.

**Comment by dionizh** [comment]
kurono/play/1 has been called by localhost (our tests):

![Screenshot 2021-03-23 at 12 50 47](https://user-images.githubusercontent.com/4784791/113898508-dbfadd80-97c3-11eb-9655-f5a6ea6cbe88.png)

Will be solved by the associated dev task: https://github.com/ocadotechnology/codeforlife-portal/pull/1409
