### ISSUE TITLE
Update Teacher Guide and Student Worksheet 3

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#419]
We need to update student worksheet 3 so it matches the word doc created by Rebecca.

**Comment by lauracumming** [comment]
Once artefacts are discovered we need to update the naming on the worksheets.

**Comment by dionizh** [comment]
Teacher's guide: https://docs.google.com/document/d/1PaJIDCA3DKk2AOZq-kZtA-miO3vhXca2/edit

Student: https://docs.google.com/document/d/1kENqEo6BgDWqoerbBOGD3Ka9tvGfOtes/edit

**Comment by dionizh** [comment]
Ready for @lauracumming and Rebecca to review :) 
https://ocadotechnology.github.io/codeforlife-teaching-resources/
