### ISSUE TITLE
Gather students' coding experience level

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#42]
Rebecca has put together a short form for the three ALD schools. She's sent them over and we are waiting for replies.

**Comment by rdcruzCFL** [comment]
https://docs.google.com/forms/d/1AzoEU77SJ1x4dCwlnEWp2ZIOkK2apJJ0IEtl9jPDoNE/edit#responses

Beaconsfield High School have replied saying that they have some basic Python programming experience and have used micro:bits.
The Laureate Academy have done no programming at all, and we haven't heard from St. Albans Girls' School but Rebecca might be able to get some information from a personal contact.

Rebecca's also emailed Mick Walters from UH who does a lot of work with robotics, including outreach, to see if he might be able to help.

Once we manage to hear back from St. Albans Girls' School we will put together some suggestions.

**Comment by rdcruzCFL** [comment]
We don't think we are likely to hear from St Albans Girls' School now it is the school holidays. I think we can assume they will not have had a huge amount of experience.
