### ISSUE TITLE
Update Privacy policy

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#422]
with usability hub etc and child-friendly language

**Comment by lauracumming** [comment]
Updated and awaiting review @faucomte97 

https://docs.google.com/document/d/15xXWw7kA5pL-p7z-4DixeuMNELeUigBXDwpzhqNou5A/edit

**Comment by faucomte97** [comment]
@lauracumming Reviewed - have added quite a few comments :P

**Comment by lauracumming** [comment]
@faucomte97  ready for you again before going to Legal
