### ISSUE TITLE
Privacy Policy update emailer

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#424]
Example: 

We've updated our privacy policy and terms and conditions to detail how we are compliant with FERPA, COPPA, GDPR, CCPA, and many other privacy regulations. Our terms also now include a Data Processing Agreement covering the proper transfer of data for EU and UK customers and a Student Data Protection Addendum for US educational institutions.
 
We also removed the Google Analytics script and cookie from Replit. We still use it on the back-end, but it does not track you.
 
The following documents have been updated or added:
Privacy Policy
Terms and Conditions
Global Data Processing Agreement 
US Student Data Protection Addendum
Replit Subprocessors
 
Your continued use of Replit following this update means you agree to our updated privacy policy and terms and conditions.
 
This is a one-time legal notice sent to all Replit users, even if you've unsubscribed from marketing communications.
 
If you have any questions or concerns, please contact us at privacy@repl.it.

**Comment by lauracumming** [comment]
https://docs.google.com/document/d/1lu09R0Prkn3eW_Z7_NPCLvlzCcEJE89GIE2OS8NnKag/edit#

**Comment by lauracumming** [comment]
Ready for contributions please @razvan-pro @faucomte97

**Comment by faucomte97** [comment]
Reviewed @lauracumming :)

**Comment by lauracumming** [comment]
closing as decided we didn't need this
