### ISSUE TITLE
Look into tracing/live coding for pupils 

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#425]
Laura has suggested 
https://thonny.org/
https://codingrooms.com/
https://aroberge.github.io/friendly-traceback-docs/docs/html/index.html

as examples of live coding/debugging/tracing tools. 

1. Suggest what is needed in terms of 
- **live coding**: supporting teachers with the introduction of concepts, demonstration of algorithms
- **tracing**: practice for pupils with reading algorithms 
- **debugging**: helping pupils find errors in example programs or their code

2. Look at how Thonny, CodingRooms, Friendly-traceback or other existing facilities might be helpful

**Comment by rdcruzCFL** [comment]
Document is here
https://docs.google.com/document/d/1L9eeSwjMT7myp25sS5Vao9m4gpZ56k-7we1Sfi72ZVs/edit#heading=h.71zlj7tdwbpn
@lauracumming

**Comment by dionizh** [comment]
This has been superseded by a few new task cards to improve the console. One of them:
https://github.com/ocadotechnology/aimmo/issues/1503
