### ISSUE TITLE
Investigate if a free IDE could be pulled into Kurono for extra debugging exercises etc.

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#431]
Following on from the sprint in July, we'd like to investigate if we could capitalise on pulling in any free or open-source extensions in order to allow extra challenges or add the ability to check code, not in the Kurono world, but could work alongside it. 

This document maps out potential extension ideas:
https://docs.google.com/document/d/1tAPbj1dM805kIP5gOxfs2nUXXoTtAf9pxjudCTzPcfY/edit#heading=h.bg1xm7satma8

**Comment by lauracumming** [comment]
- Community edition of JetBrains tools
- Vs Code

**Comment by dionizh** [comment]
Investigated the use of 'friendly' module for the friendly traceback as mentioned also in #425 (thonny also uses this module). A few points:

- It is not as easy as 'plug and play', as the 'friendly' module uses plenty of styling and theme python modules which are not available easily on pyodide (tried to install them separately and had circular dependencies problem). 

- The 'friendly' module does a lot of work in styling the output on console, and this does not work well with aimmo console as we're already fudging our error output and have our own styling. 

- It's not impossible to integrate the 'friendly' module but it needs more work. We're probably better off outputting the stack trace and its clarification on an HTML panel so we can style it better. (Examples: https://codecombat.com/ and https://www.codeavengers.com/)

- Need to think more about what we want to do about the console. It currently feels frantic as it runs continuously. Even if we display a friendly traceback, it doesn't stay still and keeps rolling.

Notes on JetBrains and VSCode - not sure if these are relevant to us, as they're separate standalone tools and no browser integration as far as I can see.
