### ISSUE TITLE
Create summary of how Rebecca teaches Python

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#44]

**Comment by rdcruzCFL** [comment]
I have put a summary of this here: https://drive.google.com/drive/u/1/folders/1ENb-J8ppoO8mZqPCmHqA0Q--QRZLOoM9

Teaching programming - one approach

Sorry, I kept forgetting to add the screen shots @faucomte97

**Comment by rdcruzCFL** [comment]
This is complete from my end. Sorry, I if didn't make that clear.
