### ISSUE TITLE
Volunteering process and policies - docs for subdomain

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#443]
We need a super clear process to get involved, assign tasks etc. 
We want to allow volunteers to do other tasks too, not just dev.
All tasks need to have a clear explanation of expectations and what could be learned etc.

- [ ] Tasks process
- [ ] dev process
- [ ] workflow
- [ ] Legal ownership of code
- [ ] Github discussions etc

**Comment by dionizh** [comment]
This looks like a good template that we can probably follow in terms of organising volunteers/contributors:
https://docs.readthedocs.io/en/stable/contribute.html

**Comment by dionizh** [comment]
"GitHub is leveraging machine learning (ML) to help more people contribute to open source. We’ve launched the good first issues feature, powered by deep learning, to help new contributors find easy issues they can tackle in projects that fit their interests.

If you want to start contributing, or to attract new contributors to a project you maintain, get started with our overview of the good first issues feature."

https://github.blog/2020-01-22-how-we-built-good-first-issues/

**Comment by lauracumming** [comment]
https://miro.com/app/board/o9J_lLJFfBM=/

**Comment by lauracumming** [comment]
https://hq.girlswhocode.com/code-of-conduct
https://hq.girlswhocode.com/privacy
https://hq.girlswhocode.com/terms

**Comment by dionizh** [comment]
Copywriting for the Contributors section (originally on gitbook, may move to portal):
https://drive.google.com/drive/folders/1N-qXsM6x6vvyVuZNZSLsWJyjVPBqlZdJ
https://docs.google.com/document/d/16FhG3-Yvk52qsNZHslIr4ZbVm6lEI8ydEQt5FxkBT6U/edit?usp=sharing
