### ISSUE TITLE
Research other not-for-profit open source projects

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#445]
We would like to understand how other not-for-profit organisations are structured and supported. How they attract their customers, how they are funded, how they document their process, what they offer sponsors. This is to understand whether we could create a charity that is funded by Ocado but also funded by other companies.

- [ ] Look at open source not for profits on Github
- [ ] Look at educational not-for-profits
- [ ] Look at not for profits that are part of corporate organisations

Create a table, or similar, comparing the information and draw some conclusions from your results.

**Comment by faucomte97** [comment]
@lauracumming Shape for BM

**Comment by faucomte97** [comment]
@lauracumming Please groom

**Comment by faucomte97** [comment]
Closing for now
