### ISSUE TITLE
Investigate Kurono Release materials

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-admin#45]
We need to look at our teaching materials and see what work is needed for it to be enough to teach one/two lessons and if it makes it clear to the teachers as to where Kurono Beta Release fits into the curriculum.

**Comment by rdcruzCFL** [comment]
Yes, I think there is plenty in there for some initial testing. The tasks there should occupy a whole lesson.

https://drive.google.com/drive/folders/1qufI2lB2gUoPLE9UOrIFnRRbqfuQnyTo
**Posted resources:**
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/dd457539-83e0-4e91-bbf2-e8fd104b98b0)

**User Guide**
https://www.codeforlife.education/teach/materials/user_guide_aimmo
- Does this matter to them at this point or should we remove it? ![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/48cdbb3f-e361-4693-9b37-e64674d5826c)
- The screenshot of the code window will need updating
- Should we remove this for now? !
[image.png]
(https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/cd5554f6-da98-4761-9eff-6bf6a58c8f49)

Intermediate Python Session 1 — Teacher Guidance
https://www.codeforlife.education/teach/materials/AIMMO_session_1
- code snippets need to be updated to remove class header

Student Challenge 1
https://www.codeforlife.education/teach/materials/AIMMO_challenge_1
- code snippets need to be updated
- remove mentions of class header
- change the hint - to make the pupils do more work here
- add an explicit mention of getting stuck

Student Challenge 2
https://www.codeforlife.education/teach/materials/AIMMO_challenge_2
- update code snippets

Code Cheat Sheet
https://www.codeforlife.education/teach/materials/AIMMO_S1_1
- update code snippets
- check that these subroutines signatures are all up to date
- add an example of how to call some of the functions shown 
- "avatar_state represents intelligence that can be used to interact with the avatar in the
game:" - wording is odd. 
- "The class has three attributes", only one listed - are we exposing any others
- Actions: "There three action types: Move, Attack and Wait" - hide this for now
- hide this maybe? MoveAction(random.choice(direction.ALL_
DIRECTIONS))
- Remove mention of pickups or indicate that will be made live later?

Understanding the turn-based game
https://www.codeforlife.education/teach/materials/AIMMO_S1_3
- update code snippets

**Comment by rdcruzCFL** [comment]
@mrniket

**Comment by mrniket** [comment]
Thanks @rdcruzCFL ! I have created an issue for the remaining changes you have recommended: ocadotechnology/codeforlife-portal#1004
