### ISSUE TITLE
Rapid Router certificates are not clear, not episode/level based

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/codeforlife-admin#462]
The certificates don’t seem to correspond directly to the level/episode titles on RR, causing uncertainty on when to give the certificates to students.

From one teacher:
> So, as for the topics mastered earning a certificate, does the Loops and Repetitions level go along with the Repeat Functions certificate?
> Does the Loops and Conditions levels go along with the Until Functions certificate?
> Does the If Only level go along with the Repeat While Functions certificate?
> etc 
> etc
> That's what I'm trying to figure out.

https://storage.googleapis.com/codeforlife-assets/general_resources/CFL_Pupil_Certificates_Colour.pdf

**Comment by rdcruzCFL** [comment]
Draft: https://docs.google.com/document/d/18bizF5qkm-owOMyd-GsZJx9v0XWAEiJcAqon5J2UbUg/edit#

**Comment by lauracumming** [comment]
Thanks @rdcruzCFL I will create a new task for creation of these
