### ISSUE TITLE
Explain 'general algorithm' in Rapid Router resources

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#474]
So that it is clear that we mean regardless of where objects and roads are etc.

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/1EDX28CI_iAcdeB0paXrudlqBiHnD-iZHFvDR8Ym4kvw/edit#heading=h.ooyk3ka1xmhw

**Comment by rdcruzCFL** [comment]
I thought this was done, @lauracumming
https://docs.google.com/document/d/1EDX28CI_iAcdeB0paXrudlqBiHnD-iZHFvDR8Ym4kvw/edit

**Comment by lauracumming** [comment]
All in agreement on the new tasks from this - this can close now
