### ISSUE TITLE
Create docs for ambassadors

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#476]

**Comment by lauracumming** [comment]
https://hq.girlswhocode.com/terms
https://hq.girlswhocode.com/privacy

**Comment by lauracumming** [comment]
This is the docs we need to support the clubs

**Comment by lauracumming** [comment]
Add to Guru

**Comment by faucomte97** [comment]
Investigate process and support for becoming an ambassador in other projects
