### ISSUE TITLE
UKS3 - Session 15 - Replace n with number

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#499]
Investigate whether this can be done with Blockly. This is the admin task to update Gitbook materials.

**Comment by faucomte97** [comment]
https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit#

**Comment by evemartin** [comment]
This task will need a follow-up to update the PDF resources on Gitbook (Independent Student Resources Advanced Pt. 3 and UKS3)
