### ISSUE TITLE
Find out if we can laser cut some stuff for Micro:Bit

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-admin#51]
https://www.kitronik.co.uk/blog/project-ideas-for-the-mipower-add-on

**Comment by mrniket** [comment]
@rdcruzCFL I'm not sure if I remember correctly but did we agree that it is probably going to be cheaper to get components from kitronik?

**Comment by rdcruzCFL** [comment]
No, we were going to find out if it was possible to get the aliens laser cut. You can't buy those. It was down as a second option in that document.

**Comment by mrniket** [comment]
It's possible to get them cut in house, we just have to buy the materials and then we should be able to do it. Closing this issue as we found it is possible.
