### ISSUE TITLE
Add new fonts to Dotdigital

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#526]
See if there is a way to add our new fonts to Dotdigital.

**Comment by faucomte97** [comment]
@lauracumming Had a look today. Seems like we have to manually edit the HTML of the template / emailer to specify `"font-family: Space Grotesk, Helvetica;"` for example. Unfortunately there doesn't seem to be a way to import new fonts to select straight from the dropdown as the dropdown only houses web-safe fonts.

I tried adding the code in the newsletter template as a test but it didn't seem to render properly. We can investigate it a bit further.
