### ISSUE TITLE
Create multiple choice questions for coding club

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#541]
We would like to trial how we can measure learning alongside our clubs.
We would like to put together a short multiple-choice survey that can help text their knowledge whilst doing this club. Either stepped along the way or at the end of the course. The teacher will have to have access to the solutions and extra learning should the students not do well in the test.

**Comment by rdcruzCFL** [comment]
Document Club pilot Q&A is in Code For Life Full Time/Admin/Product/Rebecca Kanban folder.

**Comment by rdcruzCFL** [comment]
I have drafted questions for all levels. Some are very difficult to put as M/C so please let me know if you can use them as they are or if they need adjusting to M/C.

**Comment by lauracumming** [comment]
Thanks. Can you put the link here, please?

**Comment by rdcruzCFL** [comment]
I did ^^

**Comment by rdcruzCFL** [comment]
I have created both 'questions for discussion' and multiple choice assessment questions. The m/c questions cover all sessions and should be given at the end of the club.
