### ISSUE TITLE
Bug fix - Investigate Dotmailer autoresponder- link not working

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/codeforlife-admin#565]

**Comment by dionizh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Admin-5cf7f1b750c6a6242c50af4c/issues/ocadotechnology/codeforlife-admin/565?planning-poker) with ZenHub @KamilPawel @razvan-pro

**Comment by lauracumming** [comment]
We need to recreate
