### ISSUE TITLE
Recordings for Educate page

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/codeforlife-admin#566]

**Comment by dionizh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Admin-5cf7f1b750c6a6242c50af4c/issues/ocadotechnology/codeforlife-admin/566?planning-poker) with ZenHub @KamilPawel @razvan-pro

**Comment by lauracumming** [comment]
This will need editing too so it will take quite a bit of work

**Comment by lauracumming** [comment]
Guide doc is ready:https://docs.google.com/document/d/1FyMK0p5UXKzdb9Lf_oxvxSOM41gPHEHghbdE7-qG8NY/edit
