### ISSUE TITLE
New worksheets

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#573]
We'd like to try out some simple informative worksheets with a few questions at the end. These could be turned into a digital version further along the line.

- [x] Computers - hardware / how they work
- [x] Computers - safety online / passwords and security

**Comment by lauracumming** [comment]
Ready for review: https://docs.google.com/document/d/1jbdxrdNYZqjfOwpmJSPR9c15IQxSqKFI/edit?usp=sharing&ouid=108383205802561683495&rtpof=true&sd=true

**Comment by lauracumming** [comment]
These will be going into the next sprint so please review security @faucomte97

**Comment by faucomte97** [comment]
Looks great to me, added a couple of comments as suggestions for things to add that I felt were relevant :)
@lauracumming @rdcruzCFL

**Comment by lauracumming** [comment]
@rdcruzCFL Just need a sentence or two then we can close this and move to creation stage

**Comment by rdcruzCFL** [comment]
I have done this but couldn’t create it anywhere other than my personal space. Please create me a space and I will copy it over.

**Comment by rdcruzCFL** [comment]
I have recreated these in Code For Life Extras

**Comment by faucomte97** [comment]
Reviewed and added my bits too :)
