### ISSUE TITLE
Review Rapid Router levels

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#578]
With a view to removing or altering specific levels.

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit?usp=sharing

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit?usp=sharing

**Comment by lauracumming** [comment]
I have been through this and there are quite a few tasks. Once added to board we can close this.
