### ISSUE TITLE
Change text in Level 42

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#582]
https://docs.google.com/document/d/1wVtCZ38pWyccTPKOMoxz_ymV25OT2ijm4Xwuoz3Vg6w/edit#bookmark=id.xsjzhtgasdqt

**Comment by lauracumming** [comment]
Add test to explain that the general algorithm isn't always the best solution

**Comment by lauracumming** [comment]
_Would a  'general algorithm' be the best solution here?_
Can it be changed so that it finds a shorter route, or will you need a new solution?
