### ISSUE TITLE
Level 43 in RR

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#583]
https://docs.google.com/document/d/1wVtCZ38pWyccTPKOMoxz_ymV25OT2ijm4Xwuoz3Vg6w/edit#bookmark=id.l5wkqdo5jc8r

**Comment by rdcruzCFL** [comment]
You had suggested: 
Would a  'general algorithm' be the best solution here?
Can it be changed so that it finds a shorter route, or will you need a new solution?

I am not sure that pupils will understand the term 'general algorithm'.
How about:
The code you have been using in the last few levels won't work here. Can you write something that uses still uses loops?

**Comment by lauracumming** [comment]
Sounds good

**Comment by lauracumming** [comment]
The code you have been using in the last few levels won't work here. Can you write something that still uses loops?
