### ISSUE TITLE
Level 48 in RR

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#584]
https://docs.google.com/document/d/1wVtCZ38pWyccTPKOMoxz_ymV25OT2ijm4Xwuoz3Vg6w/edit#bookmark=id.d730ad4tnw40

Add a house on every branch.

**Comment by lauracumming** [comment]
This is a dev task

**Comment by lauracumming** [comment]
We did this. :)
