### ISSUE TITLE
KS3 RR Teaching Materials 

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#586]
IKS3 - Session 10 - Sheet 1: recommend replacing “We’re going on a bear hunt” with something more age-appropriate. 
UKS3 - Session 13: In the vocabulary box, print() is missing its brackets and has an initial capital. This is inconsistent.
UKS3 - Session 14: Recommend using a main() subroutine rather than having the main code at the bottom. This is poor practice. This is linked to another task #???

**Comment by lauracumming** [comment]
Need to come up with an alternative for bear hunt. @rdcruzCFL please edit in Gitbook directly.

**Comment by rdcruzCFL** [comment]
I have done the second two tasks. I cannot find anything to replace the Bear Hunt

**Comment by lauracumming** [comment]
@rdcruzCFL Do we need to update all Python levels with main(), the resources seem to only have it on session 14?

**Comment by lauracumming** [comment]
@rdcruzCFL 👆

**Comment by rdcruzCFL** [comment]
I didn't look before that as that was the session they were introduced. I have checked 15 and 16 and they don't have subroutines. Which sheets do you mean? @lauracumming

**Comment by lauracumming** [comment]
we have competed the work on this apart from Bear hunt, so I am closing
