### ISSUE TITLE
While Loop Lesson amendments 

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#588]
- [x] Apply learning from testing
- [x] Adjust slides

https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit#bookmark=id.hqu3c8e5u0pm

**Comment by lauracumming** [comment]
@rdcruzCFL Please create the changes in a private Gitbook space, and we will replicate this for dev when we are ready

**Comment by lauracumming** [comment]
I think this is a duplicate

**Comment by lauracumming** [comment]
Can we close this ticket now @rdcruzCFL

**Comment by rdcruzCFL** [comment]
@lauracumming  As far as I am concerned, yes. Have you done the slides?

**Comment by rdcruzCFL** [comment]
@lauracumming  draft slides with branding
https://docs.google.com/presentation/d/1E2XJ5qUJ2iboSTvnH6SNfw7TOJpVgezlbHauJ_e1j7s/edit#slide=id.g22d5689d7c2_0_77

**Comment by lauracumming** [comment]
Great. Closing
