### ISSUE TITLE
Subroutine definitions in RR

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#589]
Change the subroutine definition in Rapid Router to use main() or start() as a main subroutine rather than having that code at the bottom of the program.

See https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit#bookmark=id.q5w3k6ckmtmw

**Comment by lauracumming** [comment]
This is a Gitbook task and a dev task so I will replicate in Dev

**Comment by faucomte97** [comment]
Done.
