### ISSUE TITLE
Redevelop Python levels and help for specific levels (while loops, variables) - part 1

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#595]
Refer to https://docs.google.com/document/d/145L-b6qFSpJD-J33BcoiI8XeTTzjG--3Ys0Y9KjGKF4/edit?pli=1

Redevelop all Python levels in Rapid Router to incorporate teaching materials 

Part 1: breakdown task and plan levels

**Comment by rdcruzCFL** [comment]
Part 1: redevelop Introduction to Python levels to use while loops instead of for loops. This part is done. 
https://docs.google.com/document/d/1Hw298NZBw7panydtQwSE0ONSorsW-OOarVOflz_I9yk/edit?pli=1#

**Comment by faucomte97** [comment]
@rdcruzCFL @lauracumming Looks good to me :)

**Comment by lauracumming** [comment]
Closing as next task is to create supporting material for this
