### ISSUE TITLE
Redevelop teaching materials in Rapid Router to incorporate new While/For loop levels - Part 2

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#611]
This is the teaching resources that will go with the new/adapted levels

**Comment by lauracumming** [comment]
refer to: https://docs.google.com/document/d/1Hw298NZBw7panydtQwSE0ONSorsW-OOarVOflz_I9yk/edit?pli=1#

**Comment by lauracumming** [comment]
This needs to be made into an Epic and broken down into dev tasks now

**Comment by faucomte97** [comment]
https://docs.google.com/document/d/1TmyBhl73koH0olUaCCKAQv3NB1CRIoa8afehx7OEJ_I/edit

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/14qjWrbvUX6qONgiYYBsW5KpjpfQR9liYudIuInmFZMU/edit

**Comment by lauracumming** [comment]
Levels chosen for testing @rdcruzCFL
