### ISSUE TITLE
Create new set of material for use with Pyodide (in Kurono)- Part 1 (outputs, operators and data)

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#612]
- [ ] Planning
- [ ] Scope agreed
- [ ] Part 1 material created

Audience: Teachers, pupils, independent learners. Year 8, 9 or 10

Intention: An introductory course in programming with Python to cover topics up to and including iteration with conditions.

Limitations: Pupils will need other experiences of using Python outside Rapid Router to cover the requirements of the GCSE courses.

**Part 1** 

- Output – using print(), common errors, comma-separating
- Mathematical operators – basic maths operators plus **, // and %
- Data types - integers, floats, strings and Booleans
- Variables
- Naming conventions
-

**Comment by lauracumming** [comment]
https://docs.google.com/document/d/1R_XzgGRW3-Y2Io2QqTKrEM-e641g4WE1/edit?usp=sharing&ouid=108383205802561683495&rtpof=true&sd=true

**Comment by rdcruzCFL** [comment]
Waiting for pyodide sandbox or installation to add screenshots

**Comment by lauracumming** [comment]
This has been superseded by Raspberry Pi stuff i think @rdcruzCFL ?

**Comment by lauracumming** [comment]
Superseded
