### ISSUE TITLE
Adult Code for Life Club Pack

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#616]
More about writing in Python
Turn this into instructions for the teacher.

Plus, they want a bit more Python at the end. Tweak where you think is needed for lower ages, please.

**Comment by lauracumming** [comment]
I have consolidated the slides and the pack now. Ready for review and edit by @rdcruzCFL

**Comment by lauracumming** [comment]
Rebecca reviewing and adding to adult pack

**Comment by lauracumming** [comment]
@rdcruzCFL needs to update club guide to match slides

**Comment by rdcruzCFL** [comment]
New document is here: https://drive.google.com/drive/folders/1sXeMPKp2Hkbx54Ma3u207GU6stAupQ3I
In progress.
