### ISSUE TITLE
New presentation for school / code club workshops

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#65]
This is for when we have Kurono Common Room list of teachers/schools set up.

**Comment by lauracumming** [comment]
https://docs.google.com/presentation/d/1Moswq_YwpY0K5TB4rfusdZoimvMR91rvjimGIepOlqI/edit#slide=id.g6b03f5c83d_0_15

**Comment by mrniket** [comment]
Looks great and inspiring 😊 👍
