### ISSUE TITLE
May/June Newsletter 

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#659]
Newsletter to include:

- Updates on what we have been working on
- Career focus
- Computing history
- Challenges

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/10npbosiLHG8J2qGe3l4jzHI7DEn97ck3hd92oZ_tNkI/edit#heading=h.qfpt9c88pom8

**Comment by lauracumming** [comment]
We are thinking of also adding in some updates - we have changed the variable my_van everywhere for example.

**Comment by lauracumming** [comment]
I will move to the Newsletter folder with the others

**Comment by lauracumming** [comment]
Approved by comms
