### ISSUE TITLE
Recheck club material

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#661]
Now we have updated the variable my_van, we need to go through all of the slides and supporting material and update them.

**Comment by lauracumming** [comment]
I have started this but there are some additions to the adult slides that I don't understand @rdcruzCFL Please can you take a look?

**Comment by lauracumming** [comment]
https://drive.google.com/drive/folders/1IeT0_w1QI3Zw7UgSd05hT0fpUgg3VWJY?usp=sharing

**Comment by lauracumming** [comment]
Slides in the club folder

**Comment by rdcruzCFL** [comment]
I have done this
