### ISSUE TITLE
Test and put in place process to restore site and games from back up

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/codeforlife-admin#675]
- [ ] Clone the SQL instance
- [ ] Point `dev` to the new SQL instance
- [ ] Make some changes to the DB (e.g. create an account or change names)
- [ ] Wait 1 day for automatic backup
- [ ] Make some other changes to the DB
- [ ] Restore the latest backup on the new SQL instance (⚠ make sure it's the cloned one, not the original!)
- [ ] Check the latest changes are not on the dev instance anymore
- [ ] Check the first changes are still there
- [ ] Document this whole process

**Comment by faucomte97** [comment]
LGTM
