### ISSUE TITLE
Primary coding club sessions

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#680]
- [x] Adjust sessions to ensure they are equal length as testing reported that session 3 was a little short

**Comment by rdcruzCFL** [comment]
I have added an offline exercise to session 3 before the Share and Review. There is a new sheet S3 Resource sheet 2

**Comment by lauracumming** [comment]
Just saw the above - thanks @rdcruzCFL 
We need to add some homework to the adult course please to reduce the leap from 4 to 5 and 6.
