### ISSUE TITLE
Videos for Rapid Router onboarding

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#73]
Assia has asked me to produce some onboarding videos to help teachers get started using Rapid Router. I am hoping to get one or two of these filmed over half term (w/c 21st and 28th October)

The document here https://docs.google.com/document/d/19ydU8nfnPzwfJHoqH8jFhWx0JOzo0u-7TXLtOZ-F4co/edit#  is a work-in-progress script. 

Here are the draft video titles:
1. Overview - what is Rapid Router?
2. Getting started - creating a user, a school and class; teacher dashboard; managing classes
3. Teaching resources - where and how?
4. Algorithmic thinking - how to teach the fundamentals of programming
5. Sequence, selection and repetition - step-by-step learning of concepts
6. KS3 Introduction to Python - Unique Blockly / Python split interface

Please review this as I work on it. I have finished the notes for video 1 and part of video 2 (6/10). I will also share this document with Leila.

**Comment by mrniket** [comment]
There has been radio-silence on this, closing for now
