### ISSUE TITLE
Design Cow levels

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#771]
We have introduced cows to the level creator. They can be used with if statements.
If the user doesn't sound the horn the character will crash into the cow. 

We now need to decide where some cow levels can sit to add variation to the if/else section.

**Comment by rdcruzCFL** [comment]
- Level 38 - see RDC current work for image
- Can we change the route for level 39 completely and add cows?
- Can we change level 49 to include cows as well?

**Comment by lauracumming** [comment]
Needs review still

**Comment by lauracumming** [comment]
Laura to create dev task
