### ISSUE TITLE
Admin - Write comms for drop-in infrastructure and create presentation

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#775]
- [ ] Write comms for Infrastructure Presentation and Q&A - use research and science slack channel for invites
- [ ] Create presentation
- [ ] Book and plan to record session

**Comment by SKairinos** [comment]
https://docs.google.com/presentation/d/1DaR_hIcnqHBjTCUENGM9fCn5QdHMpksNe8sESNZ84j0/edit?usp=sharing
