### ISSUE TITLE
Data task - Investigate the spike of non-returning teachers in Dec'22

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#777]

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Admin-5cf7f1b750c6a6242c50af4c/issues/ocadotechnology/codeforlife-admin/777?planning-poker) with Zenhub @faucomte97 @KamilPawel

**Comment by SKairinos** [comment]
Deleted all bot users
