### ISSUE TITLE
Newsletter exercise

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#787]
We need to add an exercise to the newsletter.
Topic is AI. Can it be related somehow?

**Comment by rdcruzCFL** [comment]
@lauracumming I have sent you a message in here https://docs.google.com/document/d/1ejX3bVvHVgmf_iTJfRVI-DSKxHYA2xF9X8X93LjkEEY/edit

**Comment by lauracumming** [comment]
Back to you :)
