### ISSUE TITLE
Data mining - completed levels 

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#798]
We would like to track the data in the level creator feature.

- [x] How many levels created (by teacher, by student, by independent)
- [ ] How many levels shared (by teacher, by student)
- [x] How many levels played (from shared)

**Comment by KamilPawel** [comment]
Here are the tables, will create another task to possibly make a migration for user data to include possibly usertype?[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2c89c724af8558a3b36e875a2256d1fa126ec759/image.png)

**Comment by lauracumming** [comment]
Great, thanks @KamilPawel 
We can close this once you have created the new task. 👍
