### ISSUE TITLE
Investigate delay in Kurono

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#813]
Dev task: https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/aimmo/1755

Problem: The simulation seems to have a slight delay to it.
This can be seen when clicking the "Run Code" button, the new code is only actually actioned by the Avatar 1-2 turns after the user clicks. The logs seem to be somewhat faster to update.

Another symptom of this is when moving randomly around the map and logging when the user tries to move towards an obstacle. The log will appear right at the start of the turn whereas the Avatar is still a turn behind, so the log appears when the Avatar is still moving which is confusing.

We need to identify exactly what the issue is as well as potential ways to fix it.

**Comment by lauracumming** [comment]
Stale
