### ISSUE TITLE
Replace Raz with a bot

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#819]

**Comment by lauracumming** [comment]
🤖

**Comment by faucomte97** [comment]
We also still need it in
- https://github.com/ocadotechnology/rapid-router
- https://github.com/ocadotechnology/aimmo

**Comment by lauracumming** [comment]
How much effort does this requirre please @faucomte97

**Comment by lauracumming** [comment]
@faucomte97

**Comment by faucomte97** [comment]
@lauracumming Barely any
