### ISSUE TITLE
Code for Life / Ocado Swag

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#82]
Find out what freebies we can offer teachers such as Ocado/Code for Life stickers and other marketing items. 
- [x] Approach marketing 
- [ ] Get stickers printed if necessary

**Comment by lauracumming** [comment]
https://docs.google.com/spreadsheets/d/1lZBd5OAvWmXSmv2is7L82V3XYZFXlyuLVdQ4h9M4FUc/edit?usp=sharing

**Comment by lauracumming** [comment]
Assia and I will discuss next week

**Comment by mrniket** [comment]
Looks great! I like the notebook/leaflet exaplaining narrative part. It would be cool to add more lore into the game 😊 

I wonder if we can use some of Ocado Technology's swag as well? It might save costs and also help the wider organisation promote itself as a technology company. 

They have some bags/pens and notebooks I think.

It's also worth noting that we have lots of stickers already and that they have been useful in several other occasions (most particularly the BETT show)

**Comment by mrniket** [comment]
@lauracumming Have we approached other parts of the company to see if we can use some of the existing swag OT makes?

**Comment by lauracumming** [comment]
Getting closer to the pot of gold at the end of the rainbow...
