### ISSUE TITLE
Bridge the gap between Python in Rapid Router and Kurono - Lesson 5

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#822]
If we are going to create an introduction to Python course then the recommended route is: 

- Output and operators 
- Variables and datatypes 
- Input and casting (int and float) 
- Selection 
- Iteration (while loops) with Rapid Router and standalone Python 
- Indeterminate Loops with Rapid Router and standalone Python 
- Selection in a loop with Rapid Router and standalone Python 
- String manipulation 
- Lists 
- For loops 
- Subroutines

This will be the lesson that pulls the lessons together with the While Loop lessons.

**Comment by lauracumming** [comment]
Duplicate

**Comment by rdcruzCFL** [comment]
@lauracumming  I can't edit this but please would you add **Indeterminate Loops** before **Selection in a Loop** above?
'Lessons' 5 and 6 cover **Iteration (while loops) with Rapid Router and standalone Python**

**Comment by lauracumming** [comment]
@rdcruzCFL  Is that what you meant?

**Comment by rdcruzCFL** [comment]
@lauracumming Yes, thank you. I have completed lessons 5 and 6 in the workspace area.
