### ISSUE TITLE
New teaching material session 2

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#829]

**Comment by rdcruzCFL** [comment]
Lesson presentation is here: https://drive.google.com/drive/folders/1odmoVVCVTDmVmzRH2oZLCcy1SoT2sK7q

**Comment by lauracumming** [comment]
@rdcruzCFL Looks great. Happy for student worksheet to be created now. 👍

**Comment by rdcruzCFL** [comment]
@lauracumming I have done this and put it in the handouts folder
