### ISSUE TITLE
Select 10 teachers from applicants

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#83]
This is when we look at the screening data and decide which 10 to select to move forward with.

**Comment by lauracumming** [comment]
We will review our applications and come up with a new strategy to extract information in order to progress with the Kurono community. 

We can still start to look at setting up the Slack channel etc in the meantime to be ready for the 'members'.

**Comment by lauracumming** [comment]
We think that it would be better not to restrict to 10, but to get the community started and see how it develops. We have currently have 38 sign ups to invite to the Slack channel. They are mainly UK and Scandinavia.
