### ISSUE TITLE
Lesson plan for Rapid Router testing

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#838]
A chance to test some of our new section questions if possible. 
We have approx 2 hrs, Yr6.

1 desktop PC between two students, but laptops available should we need.

**Comment by lauracumming** [comment]
[Doc here](https://docs.google.com/document/d/1NJsIUkQa3g6vTqVUOpkBEIX7tjYXcOmRI1LzFA2wPeY/edit?usp=sharing)

**Comment by rdcruzCFL** [comment]
This is complete from my end
