### ISSUE TITLE
Review new portal

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-admin#839]
The new portal can be reviewed at https://production-portal-dot-decent-digit-629.appspot.com/

Known issues that will be fixed:
- each time you load a new page, the cookie banner shows up. this is because the site re-renders each time you go to a new page (it shouldn't).

Below are the following pages we have created.

General
- [x] [/ (a.k.a. home)](https://production-portal-dot-decent-digit-629.appspot.com/)
- [x] [/about-us](https://production-portal-dot-decent-digit-629.appspot.com/about-us)
- [x] [/coding-clubs](https://production-portal-dot-decent-digit-629.appspot.com/coding-clubs)
- [x] [/get-involved](https://production-portal-dot-decent-digit-629.appspot.com/get-involved)
- [x] [/contribute](https://production-portal-dot-decent-digit-629.appspot.com/contribute)
- [x] [/home-learning](https://production-portal-dot-decent-digit-629.appspot.com/home-learning)
- [x] [/privacy-notice/privacy-notice](https://production-portal-dot-decent-digit-629.appspot.com/privacy-notice/privacy-notice)
- [x] [/terms-of-use/terms-of-use](https://production-portal-dot-decent-digit-629.appspot.com/terms-of-use/terms-of-use)
- [x] [/communication-preferences](https://production-portal-dot-decent-digit-629.appspot.com/communication-preferences)
Error
- [x] [/error/forbidden](https://production-portal-dot-decent-digit-629.appspot.com/error/forbidden)
- [x] [/error/page-not-found](https://production-portal-dot-decent-digit-629.appspot.com/error/page-not-found)
- [x] [/error/internal-server-error](https://production-portal-dot-decent-digit-629.appspot.com/error/internal-server-error)
- [x] [/error/too-many-requests/teacher](https://production-portal-dot-decent-digit-629.appspot.com/error/too-many-requests/teacher)
- [x] [/error/too-many-requests/student](https://production-portal-dot-decent-digit-629.appspot.com/error/too-many-requests/student)
- [x] [/error/too-many-requests/independent](https://production-portal-dot-decent-digit-629.appspot.com/error/too-many-requests/independent)
Login
- [x] [/login/teacher](https://production-portal-dot-decent-digit-629.appspot.com/login/teacher)
- [x] [/login/teacher/2fa](https://production-portal-dot-decent-digit-629.appspot.com/login/teacher/2fa)
- [x] [/login/teacher/backupToken](https://production-portal-dot-decent-digit-629.appspot.com/login/teacher/backupToken)
- [x] [/login/student](https://production-portal-dot-decent-digit-629.appspot.com/login/student)
- [x] [/login/independent](https://production-portal-dot-decent-digit-629.appspot.com/login/independent)
Reset Password
- [x] [/reset-password/teacher](https://production-portal-dot-decent-digit-629.appspot.com/reset-password/teacher)
- [x] [/reset-password/independent](https://production-portal-dot-decent-digit-629.appspot.com/reset-password/independent)
Register
- [x] [/register](https://production-portal-dot-decent-digit-629.appspot.com/register)
- [x] [/register/email-verification/teacher/?success=true](https://production-portal-dot-decent-digit-629.appspot.com/register/email-verification/teacher/?success=true)
- [x] [/register/email-verification/teacher/?success=false](https://production-portal-dot-decent-digit-629.appspot.com/register/email-verification/teacher/?success=false)
- [x] [/register/email-verification/independent/?success=true](https://production-portal-dot-decent-digit-629.appspot.com/register/email-verification/independent/?success=true)
- [x] [/register/email-verification/independent/?success=false](https://production-portal-dot-decent-digit-629.appspot.com/register/email-verification/independent/?success=false)
Teacher
- [x] [/teacher](https://production-portal-dot-decent-digit-629.appspot.com/teacher)
- [x] [/teacher/onboarding](https://production-portal-dot-decent-digit-629.appspot.com/teacher/onboarding)
- [x] [/teacher/dashboard/school](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/school)
- [x] [/teacher/dashboard/classes](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes)
- [x] [/teacher/dashboard/classes/AB123](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123)
- [x] [/teacher/dashboard/classes/AB123/additional](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123/additional)
- [x] [/teacher/dashboard/classes/AB123/edit/?studentIds={studentIds}](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123/edit/?studentIds=1)
- [x] [/teacher/dashboard/classes/AB123/reset/?studentIds={studentIds}](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123/reset/?studentIds=1)
- [x] [/teacher/dashboard/classes/AB123/move/?studentIds={studentIds}](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123/move/?studentIds=1)
- [x] [/teacher/dashboard/classes/AB123/release/?studentIds={studentIds}](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123/release/?studentIds=1)
- [x] [/teacher/dashboard/account](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/account)
- [x] [/teacher/dashboard/account/setup-2fa](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/account/setup-2fa)
- [x] [/teacher/dashboard/account/backup-tokens](https://production-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/account/backup-tokens)
Student
- [x] [/student](https://production-portal-dot-decent-digit-629.appspot.com/student)
- [x] [/student/dashboard/dependent](https://production-portal-dot-decent-digit-629.appspot.com/student/dashboard/dependent)
- [x] [/student/dashboard/dependent/account](https://production-portal-dot-decent-digit-629.appspot.com/student/dashboard/dependent/account)
- [x] [/student/dashboard/independent](https://production-portal-dot-decent-digit-629.appspot.com/student/dashboard/independent)
- [x] [/student/dashboard/independent/account](https://production-portal-dot-decent-digit-629.appspot.com/student/dashboard/independent/account)
- [x] [/student/dashboard/independent/join](https://production-portal-dot-decent-digit-629.appspot.com/student/dashboard/independent/join)

**Comment by lauracumming** [comment]
I'm not repeating things that I assume will be changed globally.

**Comment by lauracumming** [comment]
We may need to readdress the design of pages with bulk text (legal etc) at a later date as the line length is super long now. 
I'll add a ticket for UX

**Comment by lauracumming** [comment]
These URLs are missing an 'I'
/student/dashboard/dependent
 /student/dashboard/dependent/account
