### ISSUE TITLE
Set up Code for Life public Slack workspace

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/codeforlife-admin#87]
### Description ###
Creating a C4L public Slack workspace we can add the selected teachers for the Kurono common room and facilitate communication/organise events/etc.

### Requirements ###
- [x] Create a "code of conduct" for the workspace
- [x] Create a Slack workspace
- [x] Set up necessary channels and permissions

### Copywrite requirements ###
- [x] Create copywrite for PR announcement describing the workspace
- [x] Create copywrite for describing channels and rules

**Comment by mrniket** [comment]
We already have a slack workspace but we should set it up properly code-for-life.slack.com

**Comment by lauracumming** [comment]
I am working on the Code of conduct

**Comment by lauracumming** [comment]
Ready for review please @mrniket

**Comment by faucomte97** [comment]
Looks good to me, made a few tiny changes but nothing major :)

**Comment by faucomte97** [comment]
I also created a Kurono Common Room slack workspace: https://kurono-common-room.slack.com, as we didn't have any way of editing permissions / members.
