### ISSUE TITLE
2FA (part 1) - investigate best practices

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#870]
Investigate 2FA best practices and which libraries we should be using.

**Comment by SKairinos** [comment]
We are currently using the packages:
1. [django-two-factor-auth](https://github.com/jazzband/django-two-factor-auth) to integrate two factor auth into django's templates.
2. [django-otp](https://github.com/django-otp/django-otp) for OTP generation and validation. django-two-factor-auth is built on top of this.

My recommendation is to replace these packages with:
1. [pyotp](https://github.com/pyauth/pyotp) to generate and validate OTP codes
2. [qrcode](https://github.com/lincolnloop/python-qrcode) to generate QR codes.

The main justification for replacing django-two-factor-auth is that it's tightly coupled with django's templates, which we are no longer using in favour of react. Furthermore, pyotp is more popular and widely used than django-otp, so we can expect greater community support.

**WARNING**: we should carefully read pyotp's security checklist and ensure we're following best practices.

Once we generate an OTP code with pyotp, we can follow the example on pyotp's documentation to generate qrcodes using the qrcode package. For optimal resolution, we should generate the qrcodes as SVG's, not PNG. For this we'll need to install the pillow extension with the qrcode packages: `pip install "qrcode[pil]"`. The ideal image_factory setting for us seems to be `qrcode.image.svg.SvgPathFillImage`, which fills the background of the SVG with white. Then, we can return the SVG as a string or binary to the front end.

Lastly, as [confirmed by DRF](https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication), we should always inherit django's LoginView when implementing our login view.

**Comment by SKairinos** [comment]
In order to switch the users to the new pyotp lib, we'll pre-register all users with 2FA enabled and send them their QR code via email.
