### ISSUE TITLE
investigate how to authenticate with google cloud SQL

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#875]

**Comment by faucomte97** [comment]
https://cloud.google.com/sql/docs/mysql/connect-auth-proxy#connect-to-proxy

**Comment by faucomte97** [comment]
Write up findings in Gitbook before closing

**Comment by SKairinos** [comment]
The investigation discovered that the way we connect to our db server is on a VPC network via its private IP.

Initially, we were confused why we weren't connecting to our db server via its public IP with username and password. Connecting via its private IP is the recommended approach and is safer as only our cloud resources can join the network, eliminating the concern of secret keys being leaked.

The investigation had 2 major findings:

1. Our micro-services on app engine can connect to the VPC network via a [VPC access connector](https://cloud.google.com/appengine/docs/standard/connecting-vpc#configuring). In addition to connecting to the network, we'll need to configure our database settings in Django. Namely, the db's name, host, user and engine.

2. We can connect locally from our machines to the db server by [proxying requests to the VPC network](https://cloud.google.com/sql/docs/mysql/connect-auth-proxy#connect-to-proxy). Once the proxy is created, you can log into the database with a user registered on the db server. Logging in via proxy requires you to pass the user's password.
