### ISSUE TITLE
SQL queries on Gitbook

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#902]
If we fail to reference exiting queries and are forced to copy/paste the same subqueries in multiple queries, we would like to document our core SQL queries so that our data mining is clean and consistent.
An example of a core query is retrieving all the active users.

**Comment by SKairinos** [comment]
Do I need to edit [this](https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/processes-and-strategies/bigquery-best-practices-with-sql) existing doc?

**Comment by lauracumming** [comment]
Yes please

**Comment by lauracumming** [comment]
Needs to be usable by all members of the team

**Comment by SKairinos** [comment]
[PR is here](https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/~/changes/52/processes-and-strategies/working-with-bigquery)

**Comment by SKairinos** [comment]
[For later. How to update data in BQ](https://hevodata.com/learn/bigquery-insert-and-update/)

**Comment by lauracumming** [comment]
@faucomte97 Don't forget to review please.
