### ISSUE TITLE
"(non)returning" -> "(un)verified"

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#903]
[Looker Studio](https://lookerstudio.google.com/reporting/66482b38-4a70-422a-9099-9ccda493bc65/page/0PodB)

In an effort to standardise our terminology, we need to change all mentions of "(non)returning users" to "(un)verified users" on Looker Studio.

This terminology is preferred as it more clearly communicates that these are the users that have not yet verified their email addresses. Therefore, "active" users must be a subset of "verified" users.

We need to investigate where and how these changes should be made. Key questions:

1. Can we just simply update the "data labels" / "user friendly tags" on Looker Studio?
2. Or do we also need to update the queries on BigQuery, which Looker Studio is pulling the data from?

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-Admin-5cf7f1b750c6a6242c50af4c/issues/ocadotechnology/codeforlife-admin/903?planning-poker) with Zenhub @SKairinos @faucomte97

**Comment by SKairinos** [comment]
I have discovered that "returning" metric was a calculated field defined in Looker Studio. Therefore, they only need to be edited up LS, and not BQ.

I rename the "real_user" calculated field to "is_verified" and updated it to return the strings "Verified" or "Unverified", depending on whether a user's last login is null. It didn't seem necessary to create a separate implementation task as it only took a min.
