### ISSUE TITLE
Roadmap planning

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#909]
- [ ] Plan roadmap and define KPIs/ goals for 2024

**Comment by SKairinos** [comment]
@lauracumming, @faucomte97 and I finished ordering and defining the epics. You can find the link to the doc [in the card](https://app.zenhub.com/workspaces/code-for-life-admin-5cf7f1b750c6a6242c50af4c/issues/gh/ocadotechnology/codeforlife-admin/907).
