### ISSUE TITLE
data strategy pt.1

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#917]
In order to embed findings for investigation tasks, we would like to demonstrate findings to the team on Big Query and Lookerstudio.

- [x] walk through of findings

**Comment by SKairinos** [comment]
https://app.gitbook.com/o/-M_6U74XVytl1uT1MyQy/s/4B50MUwkxITPKcTyHt3z/~/changes/56/data/storage

**Comment by SKairinos** [comment]
data backups

**Comment by SKairinos** [comment]
@lauracumming, @faucomte97, ready for review. Added a section for data backups.
Can one or both of you please proof read my PR. Just to make sure all clear and correct.

**Comment by SKairinos** [comment]
Please note, I have added legal task #968 to the backlog

**Comment by lauracumming** [comment]
It wouldn't let me comment on the doc for some reason. :( These are my comments:

Are you adding any of these tasks to the data epic? If not I can add in some time to a sprint to add some data tasks so we don't forget anything and start to align to this over time?

Should we say what the steps are if a user gets in touch and asks for their data to be deleted, is step 1: forward email to data protection team, step 2...
