### ISSUE TITLE
rapid router attempt collection

### ISSUE THREAD

**Issue by dionizh** [ocadotechnology/codeforlife-admin#921]
Investigate if RR attempts are being correctly collected and reported on Looker Studio.

- Check if the data is being queried correctly
- Update query if needed
- Create table in Looker studio

**Comment by SKairinos** [comment]
@lauracumming, [which table](https://lookerstudio.google.com/reporting/66482b38-4a70-422a-9099-9ccda493bc65/page/0PodB) are your referring to?

**Comment by SKairinos** [comment]
After looking into this, I don't understand:

1. Why do we record an attempt when we load a level? Note this does not happen when navigating to a level via the history; should it?
2. When are we supposed to record the start_time time?
3. When are we supposed to record the finish_time time?

Without understanding the intended functionality, I cannot proceed.

**Comment by faucomte97** [comment]
@SKairinos 

1. An Attempt is not linked to loading a level, it's linked to a player's attempt at solving a level. Essentially, an Attempt is created every time they press the "Play" or "Fast" button.
2. start_time _should_ be when the user presses the "Play" button.
3. finish_time is either when: a) the van reaches the goal node, b) the van runs out of fuel, c) the van runs a red light, d) the van crashes and potentially e) the van runs out of instructions

**Comment by SKairinos** [comment]
My findings:

We have issues on both in code and BigQuery.

**Code**
- Attempts are unnecessarily collected when the level loads.
- The time stamps are not being collected correctly.

**BigQuery**
- The game_level table is not being warehoused. Therefore, we cannot blend the data between the attempts and the levels (to know which levels were attempted).
