### ISSUE TITLE
CFL Findings 193, 205 & 206 - investigation

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#923]
[Findings](https://docs.google.com/spreadsheets/d/1B4s9ui4zN-RkJBitfSCU0lZirS530q6l74UdyloA3eo/edit#gid=0)

**Comment by SKairinos** [comment]
[see comment](https://docs.google.com/spreadsheets/d/1B4s9ui4zN-RkJBitfSCU0lZirS530q6l74UdyloA3eo/edit?disco=AAAA_8O6T4w)
