### ISSUE TITLE
google tag manager

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#927]
Investigate how to:

- [x] record clicks on specific UI elements with Google Tag Manager.
- [x] save this data on Google Analytics. 
- [x] sync the data between Google Analytics and Looker Studio.

Previously, events on our site were being tracked by calling our API and saving them on our SQL DB. Using, GA + GTM, we should no longer need to do this.

**Comment by SKairinos** [comment]
[this tutorial](https://www.lovesdata.com/blog/google-tag-manager-button-click-tracking) sums it up quite nicely
