### ISSUE TITLE
connect dotdigital to looker studio

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#928]
Connect DotDigital to Looker Studio in way where data can automatically be synced. This means data should not have to be manually exported and imported. 

Once connected LS, create a table on LS to show data on the email campaigns, including:
1. name
2. num. of opens
3. num. of bounces

It's been suggested that one way to connect DD to LS is through Google Analytics. Another way be to potentially do it through a google sheet. References:
https://dotdigital.com/blog/qa-telling-stories-with-google-data-studio/
https://support.dotdigital.com/en/collections/5610154-google-sheets
https://support.dotdigital.com/en/articles/8198921-use-google-analytics-4-with-dotdigital

**Comment by SKairinos** [comment]
After some further investigating, we cannot import campaign report data from dotgitial to google analytics or looker studio. Originally, I thought DD google sheet integration could help us solve this problem but the concern is that DD would then have full access to ALL our google sheets. For security reasons, this is unacceptable. With this in mind, we have 2 possible solutions.

**Option 1: New Quarantined Account**

Create a new account that does not have access to the CFL drive and the google sheets in them - it will be quarantined. Then we give DD access to that accounts google sheets, so it can export the campaign reports to sheets in that account. Then we allow LS to import sheets from that account.

**Option 2: DD API (Better Option)**

Call DD's API to get the campaign reports in a daily cron job and save the results to a SQL table our production DB. Then we can save this table in our data warehouse (BigQuery). Then we can add this table as a data source in LS.
