### ISSUE TITLE
create a team keeper account

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#930]
Create a team Keeper account for the CFL team. Keeper is Ocado's approved password storage tool.

[Keeper supports teams](https://docs.keeper.io/enterprise-guide/teams).

Tasks:
- [x] Each team member must set up their own Keeper account.
- [x] Reach out to TSS to create a CFL team on Keeper.
- [x] Ask if TSS can give us admin control of the team so we don't need to keep reaching out to them.
- [x] add each CFL member to the team.
- [ ] transfer all CFL passwords to the team account.

If we cannot create a team, we can all share a common account registered to code-for-life-full-time-xd@ocado.com as a last resort.

**Comment by SKairinos** [comment]
I have reached out TSS to:
1. create my account
2. make a team
3. make @faucomte97 and I admins

decided to get the call rolling on this as sometimes TSS is very slow to respond

**Comment by SKairinos** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f54a7d22f386c40488c5d7ef83cde460e222e367/image.png)

**Comment by SKairinos** [comment]
@faucomte97 , can you check you have been added?
@lauracumming , I asked them to add you to the team also.

**Comment by SKairinos** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de4f1a8934d4c7d000e257cec129af7d90900031/image.png)

**Comment by SKairinos** [comment]
boom
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2tDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--300cb7a1f8c4daff42291ab2181f98bdbc46fea8/image.png)

**Comment by SKairinos** [comment]
@faucomte97 , you should now be able to create a shared folder, add team "Code_For_Life" and start transferring passwords to the shared folder (edit -> "move to")
