### ISSUE TITLE
sync github to gitbook

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-admin#934]
https://docs.gitbook.com/integrations/git-sync/enabling-github-sync

This will allow us to:

1. include documentation in the PRs (very important)
2. keep the docs near the code they are referencing
3. publicly track the edits to the docs in the form of commits

Complete for set up guides and any public resources, not lesson plans for now.

**Comment by SKairinos** [comment]
test

**Comment by SKairinos** [comment]
@lauracumming and @faucomte97 , test comment

**Comment by SKairinos** [comment]
sadness

**Comment by SKairinos** [comment]
test

**Comment by SKairinos** [comment]
test

**Comment by SKairinos** [comment]
test again

**Comment by lauracumming** [comment]
and another test

**Comment by SKairinos** [comment]
I have synced the "Code for Life" space to the workspace repo. I couldn't sync all the required docs as they're not correctly separated. I have created a [follow up task](https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/codeforlife-workspace/29) to separate the documentation so we can sync the rest later.

The way the syncing works is that it'll sync to the `production` branch of each service repo inside of a directory called `/docs`. Due to the branch protection rules, the production branch will reject and sync changes made from gtibook -> github. Despite GitBook supporting bi-directional syncing, this means we'll only have uni-directional syncing (github -> gtibook) in order to enforce our code promotion strategy.

**Comment by faucomte97** [comment]
@SKairinos I had another concern about this that we forgot to test yesterday.
Consider this scenario:
1. Someone makes a change in Gitbook (anywhere in the space). This change therefore is only visible in Gitbook.
2. Someone else then makes a change in Github. When the PR is submitted, Gitbook is automatically synced to Github.

Does the sync overwrite the changes that had been done in step 1? Essentially, how does the sync work, does it only look at what's been changed or does it do a complete copy-paste of the space? What about if there are conflicting changes?

**Comment by lauracumming** [comment]
We can test it. That's what i was suggesting - to just sync 1 thing to test how it works.

**Comment by lauracumming** [comment]
I'll add a test task to next sprint
