### ISSUE TITLE
kurono artefact reload bug

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-admin#936]
There is a bug in worksheet 3 where if you restart a stopped game artefacts don't show up. Investigate why this happens.

**Comment by SKairinos** [comment]
The issue is that none of the game state, including obstacles and artefacts, is persisted. To quickly fix this, we can just simply randomly regenerate the game state each time the game is restarted. Players will also need to be randomly placed.

**Comment by lauracumming** [comment]
Great. Did you create a backlog task ticket for it?

**Comment by SKairinos** [comment]
no. thank you for that!

**Comment by SKairinos** [comment]
https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/aimmo/1832

**Comment by SKairinos** [comment]
https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/aimmo/1832
