### ISSUE TITLE
 Kurono and the KS4 National Curriculum (major exam board specifications) for programming

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/codeforlife-admin#94]

**Comment by rdcruzCFL** [comment]
This is done now. It was more standard than I expected.  @mrniket

**Comment by mrniket** [comment]
here is the link: https://docs.google.com/document/d/18nov_7kutJb6gn4tx_8sbZ3JzC8BwjHEBFy_LWHl_AE/edit
