### ISSUE TITLE
Debugging exercises for Rapid Router

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#942]
We need to create some challenges around debugging for our partnership with Barefoot Computing.
This will be at the end of learning about Demand Forecasting within Ocado.

- [x] 5 x debugging exercises using Rapid Router suitable for yr 5 and 6

**Comment by rdcruzCFL** [comment]
https://docs.google.com/document/d/1ps386tcMewB1Gppsewnx1sBDCG2AYjNySEr-qYNRLig/edit
