### ISSUE TITLE
Primary presentation / demo for CAS#939

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#950]
- [ ] A running order and intro text for CAS ad.
- [ ]  A presentation on the KS1 and 2 of the resources including:

- Rapid Router

[See text here](https://docs.google.com/document/d/1UIjV_Df6fc9bzjYbJ9jlbPhXVI0OZNbQb-PjbFFh3Ao/edit#heading=h.3ebx4idpur0c)

**Comment by rdcruzCFL** [comment]
This is here https://drive.google.com/drive/u/1/folders/1NuPJGBYyzLcJ5agAM9_SJ-gMhYeHeDgm/DEMO Introduction to Rapid Router - Primary.pptx (Partnerships/Computing at School)
