### ISSUE TITLE
Reword / Rethink resources for levels 36-37 (LKS3-S4) to introduce `else`

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-admin#952]
We've recently updated the description and solution of level 36 to introduce the `else` block: https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/rapid-router/1470

The `else` block is not mentioned at all in LKS3-S4 or the resource sheets for that session. On top of that, level 37 is now no longer consistent with level 36 as it does not include the `else` block either.

- [x] Update LKS3-S4 and supporting resource sheets depending on how we decide to rework the session and when / how to introduce the `else` block.
- [x] Decide whether or not we want to update the solution for level 37 so it also uses `else`. If so, create a dev task for it.

**Comment by rdcruzCFL** [comment]
Task created for level 37 https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/zh/3

**Comment by faucomte97** [comment]
I assume so, I don't recall having made any changes since we opened this task. @rdcruzCFL's link seems to be broken.

**Comment by rdcruzCFL** [comment]
This is the one I was working on @lauracumming You said you were going to change the PDF...

**Comment by lauracumming** [comment]
I have completed the PDF and image change on Gitbook. Do we want a task for the actual level though?

**Comment by faucomte97** [comment]
@lauracumming What was the change?
