### ISSUE TITLE
Create Primary school reception mailing list in Dotdigital

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#981]
Take a look at the stats on our CFL report to find a county that is either missing or a low number of active schools and create a list from Google.

- [ ] Add to Dotdigital in preparation for send out.

**Comment by darcie-gomer** [comment]
[Google sheet](https://docs.google.com/spreadsheets/d/1eXMObiKoru0zt8abK8ZA5nKcutFpiFyzMkU_DwKw-uM/edit?usp=sharing) with list of counties where we only one school or no schools and schools to contact per county
