### ISSUE TITLE
Create Primary school reception email

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#982]
We would like to create an email that introduces the product to primary schools and directs a computer science teacher to sign up. You can use some of the text [from here](https://docs.google.com/document/d/1UIjV_Df6fc9bzjYbJ9jlbPhXVI0OZNbQb-PjbFFh3Ao/edit?usp=sharing) to inform your email.

Additionally, we would like to include the 10 year graphic in our template this year. 
Please add to the footer of the email for now.

- [x] Create Dotdigital email
- [x] Test send to team
- [x] Test send to Jelmer

**Comment by darcie-gomer** [comment]
[Drafting the email in DotDigital](https://r1-app.dotdigital.com/Campaigns/Step/EasyEditor.aspx?id=1519236)

**Comment by darcie-gomer** [comment]
Email checked by team and by Jelmer, ready to send!
