### ISSUE TITLE
CFL Bake off

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#985]
Aim of event is to gain volunteers, advertise stats and mission.

- [ ] Prep CFL Bake off - Bessemer Road - create slack posts and schedule to send out

**Comment by darcie-gomer** [comment]
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjYxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--458132449e8d7811262fe606a7b9cb28d92d6505/CFL%20BAKE%20OFF%20%282%29.png" alt="CFL BAKE OFF (2).png" />
Slacks posts scheduled for once a week up until the bake off on Tuesday 30th Jan 2024
