### ISSUE TITLE
Design Kurono insights workshop

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#995]
In order to ascertain whether or not we put effort towards Kurono, we need to present back our findings from the Kurono research in schools we completed.

This workshop should explain the approach, the numbers of teachers/students and the key results to inform our decisions.

From #4 "I'd like to have a session with the team where we go through the purpose, our audience and goals etc to realign our vision and ensure that I am aligned to the business and team."

**Comment by darcie-gomer** [comment]
[Workshop miro board](https://miro.com/app/board/uXjVNyokVXk=/?share_link_id=740567482226)
