### ISSUE TITLE
Session 1 walk through (For teacher)

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#999]

**Comment by rdcruzCFL** [comment]
@lauracumming They are just in the same folder as the slides
https://drive.google.com/drive/folders/1COQG7X83InkItxq6yjXnMCMg_XCYfFjh

**Comment by lauracumming** [comment]
Added comments here: https://docs.google.com/document/d/1rF9uoKnXENGHkKLXcct3IYgmgD91iXdm3WwF4fUmiQY/edit?usp=sharing
